README.md, docker-compose.yaml, scripts/run.sh
We claimed that running `docker compose up` would not require the repo to be needed to checkout, but we were missing to use a pushed version of the `fake-logs-generator`. Fixing that by using a recent version I just pushed.
Fixes #211
=> fix: docker-compose without building

src/pages/Explore/SelectAttributeWithValueAction.tsx, src/pages/Explore/SelectStartingPointScene.tsx, src/utils/store.ts
Fixes: https://github.com/grafana/explore-logs/issues/225
+ I have added a logic to ensure we are only storing each service name once in the local storage
=> Bring showing of favorite services on top back

src/components/Explore/LogsByService/LogsByServiceScene.tsx, src/components/Explore/LogsByService/Tabs/FieldsBreakdownScene.tsx, src/components/Explore/LogsByService/Tabs/LabelBreakdownScene.tsx
This fixes time series graphs in detected fields from showing a "Value" time series, which is the volume of the logs that are not aggregated by the label of the current query.
fixes: #67
Before:
After:
=> Remove errors from detected field queries

src/components/Context/ScenesTableContext.tsx, src/components/Context/TableColumnsContext.tsx, src/components/Explore/LogsByService/Tabs/LogsListScene.tsx, src/components/Explore/panels/tablePanel.tsx, src/components/Table/ColumnSelection/ColumnSelectionDrawerWrap.tsx, src/components/Table/ColumnSelection/LogsColumnSearch.tsx, src/components/Table/ColumnSelection/LogsTableAvailableFields.tsx, src/components/Table/LogLineCellComponent.tsx, src/components/Table/LogLinePill.tsx, src/components/Table/LogsTableHeaderWrap.tsx, src/components/Table/RawLogLineText.tsx, src/components/Table/Table.tsx, src/components/Table/TableWrap.tsx
Syncing the selected columns between scenes and react was causing bugs, and scenes doesn't need to know which columns are selected within the react table. Using react router to manually set url state keeps viz specific logic out of scenes, and is easier to maintain
=> Table: Refactor url state to use react-router 

src/Components/Index/ServiceSelectionComponent.tsx
- #258 
Set the width to 100% in md breakpoint. Setting the height or minHeight did not seem to work, but it would have been nice to make them taller. 
- [Scenes breakpoints docs](https://github.com/grafana/scenes/pull/156/files#diff-0619e5bc001b9b055c71b89fc9f9f9638fb7373bdd5f9ceaeaa03161216f46e7)
=> fix: landing page wrap

.github/workflows/build-generator.yml
We won't use the `dev` environment for now. Going to destroy any allocated resources in a PR in deployment_tools.
=> chore: change GAR to `prod`

docker-compose.yaml
We added CI to build and push the fake log generator. This PR updates the reference in the docker compose setup.
Fixes #215
How to test:
1. `docker compose pull`
2. `docker compose up`
3. Should still result in visible logs in the app.
=> chore: change to grafana's generator image

src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
In an odd turn of events, probably do to @ivanahuckova refactor the md breakpoint stacks now.
=> fix: md layout stack

src/Components/LogExplorationPage.tsx, src/Components/ServiceSelectionScene/SelectFieldButton.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/scenes.ts
1. In my case, using `newLogsExploration()` in `LogExplorationPage` have made readability/understandability of code much harder. `newLogsExploration` is just a wrapper over creating a new `IndexScene` and we are not even using `initialDS` - so that can be removed. I think it should be very obvious in code where we are creating scene and not hidden in services folder. 
```
export function newLogsExploration(initialDS?: string): IndexScene {
return new IndexScene({
initialDS,
$timeRange: new SceneTimeRange({ from: 'now-15m', to: 'now' }),
});
}
```
2. Fixing keeping `SERVICE_NAME` in sync between querying for values and then creating new query when selecting service.
=> chore: refactor for readability

src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
Brings back code removed in https://github.com/grafana/explore-logs/pull/266/files. But instead of just removing SERVICE_NAME filters, we want to remove all. I tried to see if I can find a way to remove it somewhere else, but I couldn't. So I just brought this back :( 
https://github.com/grafana/explore-logs/assets/30407135/b49a3ded-2c9c-4c6a-aa2f-d13891a42dfd
=> fix: remove bug when filters were applied when going to service search scene

src/Components/IndexScene/IndexScene.tsx, src/Components/IndexScene/PatternControls.tsx, src/Components/IndexScene/PatternTag.tsx, src/services/store.ts
This PR:
- Adds comments
- Removes state/props that we are not using - such as  `showDetails`
- `body` is not `SplitLayout` anymore as we are not using it. And instead it is `LogExplorationScene`
- moves getting/setting initial data source from local storage to `store`
- Removes following logic, that was initially there to add live tailing controls, which were removed and this is not doing anything anymore:
```
if (this.state.mode !== undefined && this.state.mode !== 'start') {
this.setState({
controls: [...this.state.controls],
});
}
```
- Removes additional logic for hiding of variable. More context in https://raintank-corp.slack.com/archives/C05FWM2DN07/p1714668329748469?thread_ts=1714667212.714819&cid=C05FWM2DN07, but basically there might be an issue when variables are not hidden. …
=> chore: clean up index scene and refactor

src/Components/ServiceScene/ServiceScene.tsx
Fixes #285
https://github.com/grafana/explore-logs/assets/1069378/4ba4c865-170c-4d6b-9b62-288188695546
=> fix(ServiceScene): reset line filter value when redirecting to start

src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
Logs panel scales to 100% now.
=> fix: service selection wrapping of items

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/routing.ts
Adds the plugin ID as `supportingQueryType` header, which translates into the `X-Query-Tags` in Grafana, and then in the `source` label in Loki (see screenshot).
NB: this does only work for "queries" not for resource calls for now.
=> feat(query-tracking): add `supportingQueryType` header

src/Components/IndexScene/PatternControls.tsx, src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx, src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/FilterByPatternsButton.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LayoutSwitcher.tsx, src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx, src/Components/ServiceScene/GoToExploreButton.tsx, src/Components/ServiceScene/LineFilter.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/Components/ServiceScene/ShareExplorationButton.tsx, src/Components/ServiceSelectionScene/SelectFieldButton.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/analytics.ts
This PR adds simple analytics for interactive elements - buttons, inputs.
I have created `reportAppInteraction = (page: 'service_selection' | 'service_details', action: string, properties?: Record<string, unknown>) => { reportInteraction(createInteractionName(page, action), properties);};` so we are aligned with events naming and also it makes it easier to test in the future (just adding console.log above `reportInteraction`). 
Fixes: https://github.com/grafana/explore-logs/issues/256
=> feat: add analytics

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/query.ts
Unifies log and volume query creation - so instead of creating the same thing in many files, we have one place with default logic that can be overridden. 
Side task - in the label and fields tabs during layout creation, we were sometimes using 'option label' and sometimes 'option value.' I have unified it.
=> chore: refactor query creation and have a single place where we create it

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/services/scenes.ts
Currently we display labels and fields as filters, even when already used, which causes them to be visible bot not interactive, i.e, clicking does nothing.
In this PR we're removing them from being listed and updating the displayed amount to match the available filters.
Before:
https://github.com/grafana/explore-logs/assets/1069378/e48ba843-9fcc-42a1-b4c6-d7fd347fb334
After:
https://github.com/grafana/explore-logs/assets/1069378/3e09f973-00a6-44ad-99d3-cd11ca0d7f48
Fixes https://github.com/grafana/explore-logs/issues/300
=> Filters: hide labels and fields if already used (and not actually interactive)

src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
Fixes https://github.com/grafana/explore-logs/issues/275
Now:
Before:
=> fix: fix extra padding in logs panel

src/Components/ServiceSelectionScene/SelectServiceButton.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
https://github.com/grafana/explore-logs/assets/8092184/cbd937d7-d6bf-4a52-966a-afa125a23ae5
In some edge cases multiple services could be selected. This PR should fix this behaviour.
Additionally, I rename the class to most suitable name.
=> fix: service button could add multiple services

src/Components/App.tsx, src/Components/LogExplorationPage.tsx, src/Components/Routes.tsx
Currently the IndexScene instantiates on every action that causes a url sync. This PR fixes and memoizes the index component, and adds the PluginPropsContext
=> fix: url sync causing complete re-instantiation

src/Components/IndexScene/IndexScene.tsx, src/Components/ServiceScene/GoToExploreButton.tsx, src/Components/ServiceScene/ServiceScene.tsx
Clicking the explore button did not include the log format. This PR has a fix to include it.
=> fix(GoToExplore): link to explore was missing log parser

src/Components/IndexScene/IndexScene.tsx
For now this disables to show more label values, as the label values previously were showing results from a wrong datasource.
In the future we can look into more sophisticated solutions.
=> fix(fields): disable tag provider

src/Components/ServiceScene/LogsVolumePanel.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/panel.test.ts, src/services/panel.ts
This PR:
1. Adds total count of logs to  in service selection in form of table on right (levels are not filterable)
- also makes time series panel 100px wider to accomodate new legend table 
3. Adds total count of logs to  in service detail in form of list on the bottom (levels are not filterable)
4. If we don't have level, instead of having `Value`, it renames it to `logs`. We could also do `unknown`, but in explore, we were just naming it `logs` which I like
5. If we don't have level, changes color to `gray` to distinguish from `info`
https://github.com/grafana/explore-logs/assets/30407135/396116d0-74f1-44dd-9a17-16770a0ee90d
Fixes: https://github.com/grafana/explore-logs/issues/217
=> feat(volume panels): add legend to volume panels with logs sum and possibility to filter in panel

src/Components/ServiceScene/ServiceScene.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
This PR disables the hover tooltips that are shown in the following video:
https://github.com/grafana/explore-logs/assets/1069378/efc0e1f9-7c36-4dc9-b09a-f7b116dfbcae
The reason is that the behavior and information it shows is potentially confusing, and the tooltip is very hard to dismiss.
=> fix(ServiceSelectionScene): disable hover tooltips

src/Components/ServiceScene/Breakdowns/FilterByPatternsButton.tsx, src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx, tests/exploreServicesBreakDown.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/218
This PR does 2 things:
1. When a pattern is already excluded, it will hide the exclude pattern button. Same with included patterns
2. When a pattern is included, all other patterns are removed from state.
https://github.com/grafana/explore-logs/assets/109082771/2e8afe1d-53d1-4933-a0fa-fb0ec1b0b3ca
=> fix(patterns): only allow a single include pattern

src/Components/ServiceScene/LineFilter.tsx
I was looking at usage tracking, and realized we were storing the contents of the line filter searches. We don't even store original queries, which are [obfuscated](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/tracking.ts#L185). Ammending that in this PR.
=> fix(LineFilter): keep track of search length and attributes but not contents

package.json, src/Components/IndexScene/PatternControls.test.tsx, src/Components/IndexScene/PatternControls.tsx, src/Components/IndexScene/PatternTag.tsx, tests/exploreServicesBreakDown.spec.ts, yarn.lock
After https://github.com/grafana/explore-logs/pull/343 we no longer allow multiple pattern filters. For that, in this PR:
- Added `lg` and `sm` sizes to `PatternTag`
- Use `lg` "Pattern" when filtering by a single pattern
- Use `lg` "Excluded pattern" when excluding a single pattern
- Use `sm` "Excluded patterns" when excluding multiple patterns
- Define the `lg` pattern tag preview size based on the screen size. The chosen value seems to nicely behave under different viewport sizes:
https://github.com/grafana/explore-logs/assets/1069378/82d9e59c-f028-4bdd-b444-df007146436b
=> Patterns: change label to singular and increase preview size

src/services/analytics.test.ts, src/services/analytics.ts
Event names should not include underscores, however the plugin id contained dashed. Those will be replaced by underscores for now.
=> feat(tracking): change event names to not include dashes

src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx, src/Components/ServiceScene/LogsListScene.tsx, tests/exploreServicesBreakDown.spec.ts
plus remove logs from logs panel
=> chore: make patterns graph smaller - the same size as logs volume

src/Components/IndexScene/IndexScene.tsx, src/Components/IndexScene/LayoutScene.tsx, src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx, src/Components/ServiceScene/LineFilter.tsx, src/Components/ServiceScene/LogsListScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
This PR extracts `LogsExplorationScene` out of `IndexScene`, and renames `LogsExplorationScene` to `LayoutScene`. The reason for the new name is that `LayoutScene` contains the header contents (Variable controls + pattern filters) and a variable body, which can be the `ServiceScene` or the `ServiceSelectionScene`, so there's no "logs exploration", but rather a combination of fixed contents + a variable body.
Other changes:
- Renamed a few `onActivate()` methods and removed the private underscore suffix. It used to be a mix of with and without underscore, and I don't think this is a pattern that we'd like to follow.
- Within `LayoutScene`, instead of accessing `IndexScene` internal state thorugh `sceneGraph`, we now use `model.parent.useState/setState`.
=> refactor(IndexScene): move LogsExplorationScene to a module and rename as LayoutScene

src/Components/ServiceScene/LineFilter.tsx, src/Components/ServiceScene/LogsListScene.tsx, src/Components/ServiceScene/ServiceScene.tsx
Moves the log volume panel inside the logs tab.
https://github.com/grafana/explore-logs/assets/8092184/eac90eeb-5582-465a-8838-b708415d34f9
=> feat(move-log-volume): moves log volume panel inside logs tab

src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx, src/services/testIds.ts, tests/appNavigation.spec.ts, tests/exploreServices.spec.ts, tests/exploreServicesBreakDown.spec.ts
Reverts grafana/explore-logs#376
Turn e2e tests back on, removes hardcoded strings that were changing since the datagenerator used in CI is returning different patterns then the generator ran locally.
=> Revert "fix: skip all e2e tests"

src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
Fixes: https://github.com/grafana/explore-logs/issues/380
Note for reviewers: As far as I can tell this doesn't change the layout in chrome/ff, but it fixes the bug where it looks like safari is calculating a different 70% then the other browsers
=> fix: use content irrelative unit to get more consistent calculations

src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Fixes: https://github.com/grafana/explore-logs/issues/373
Small viewports will scroll horizontally instead of pushing out the container width.
To reproduce on main: Find a really long pattern without any spaces to break, or go into the inspector and change the content of a pattern string within the table to something really long without any spaces.
=> fix(patterns): fix bug introduced by using viewport units in styles

.github/workflows/ci.yml, src/Components/ServiceSelectionScene/NoVolumeError.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
Added a quick feature to use the input in "Search services" to be used in the Volume API request. This enables users to search for their exact service name.
https://github.com/grafana/explore-logs/assets/8092184/3f6d6e86-9852-43ef-b2c1-a82ebe3d6fba
=> Service Search: Use search input to query volume API

src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
"Favorite" or rather previous selected services will be shown at the top of the service selection. This PR fixes a behavior where favorite services are shown even if they are not included in the response of the /volume API:
=> fix(service-selection): only show favorite services if there is data

src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
Closes https://github.com/grafana/explore-logs/issues/402
Message:
Open for suggestions for the error message. The important part is that:
- It should let the user know what happened.
- It should offer at least one workaround.
=> feat(LabelBreakdownScene): display an error message when the request fails

docs/README.md, docs/sources/_index.md
In preparation for the team starting to write draft documentation, adding the `docs/sources` folder to the repo.
=> docs: adding docs source folder

src/Components/ServiceScene/Breakdowns/FilterByPatternsButton.tsx, src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
To keep our graphs similar style, plus it is more clear how many patterns and at what time frame were detected. 
New:
Old:
=> feat(patterns): style patterns in the same way other graphs are styled

src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Fixes: https://github.com/grafana/explore-logs/issues/366
Also splits up the count/percent column into multiple columns, and tweaks a few styles:
=> Patterns: Smaller text font

src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/PatternsFrameScene.tsx, src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Having a new container gets rid of the need for useMeasure hook, which reduces the number of re-rendering we're doing in scenes. Also this tees up further work in the patterns view like text search.,
Shouldn't be much change in functionality, although now the column headers are sticky when scrolling through the patterns, and the header has been removed from the main pattern timeseries up top.
Double vertical scrollbar is still possible, for devices with small screen heights, and when many filters are applied pushing down the top of the page. Perhaps in https://github.com/grafana/explore-logs/issues/396 we should address this via measuring the height of the sticky header, or by adding the ability for the user to manually resize how much of the viewport height is dedicated to each section.
=> Chore: Refactor patterns breakdown

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/ServiceScene.tsx
Fixes https://github.com/grafana/explore-logs/issues/393
This PR:
- Adds a missing loading state to Detected Fields
- Adds an empty state to Detected fields
https://github.com/grafana/explore-logs/assets/1069378/4a132ace-561f-4437-85aa-7c8c1f2bf0fe
=> fix(FieldsBreakDownScene): add loading state and empty state

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx, src/Components/ServiceScene/LogsListScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx, src/Components/ServiceScene/PageScene.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
Fixes https://github.com/grafana/explore-logs/issues/358.
This is a temporary workaround until we have time to refactor the breakdowns into routes (see https://github.com/grafana/explore-logs/issues/351)
Shouldn't impact layout at all. Clicking on the top level nav item still takes user back to the "services" view, which is the desired functionality AFAIK.
This won't fix the browser history though. I looked at using the hook useHistory, while it somewhat worked for children routes, it throws an error when the IndexScene is loading, if we want browser history we'll need to implement a route for each page.
=> fix: wrap components in PluginPage to fix breadcrumbs

src/Components/IndexScene/LayoutScene.tsx, src/Components/ServiceScene/Breakdowns/AddToFilterButton.test.tsx, src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx, src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/services/fields.ts, src/services/scenes.ts
We had an issue where clicking on the label ad hoc filters didn't show/provide any options. This was a bug because we were not setting **labels** as **label filters** but as **detected fields**. This PR fixes it and ensures that the only label that we want to select as a detected field is `detected_level` since it is structured metadata and won't work as a label.
The PR also adds tests.
**Fixed:**
https://github.com/grafana/explore-logs/assets/30407135/6eb0fb56-dba1-49e5-8851-919aa97ccdb0
**Broken on main:**
https://github.com/grafana/explore-logs/assets/30407135/ea8a9c38-e503-45dc-85fb-41a3c59c288b
=> fix: label filter dropdown should show options

src/Components/Table/Context/TableColumnsContext.tsx, src/Components/Table/LogLineCellComponent.tsx, src/Components/Table/LogsTableHeader.tsx, src/Components/Table/LogsTableHeaderWrap.tsx, src/Components/Table/Table.tsx, src/services/logsFrame.ts
Adding backwards compatibility for legacy dataplane.
For some reason I thought the dataplane feature was required for the logs app, but I was incorrect.
=> Logs Table UI: Legacy dataplane fix

src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Fixes https://github.com/grafana/explore-logs/issues/399
=> Patterns: Use short units for count column

src/Components/ServiceScene/Breakdowns/ByFrameRepeater.tsx, src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/SearchInput.tsx
Part of https://github.com/grafana/explore-logs/issues/400
Closes https://github.com/grafana/explore-logs/issues/433
This PR adds filtering to fields values. This filtering has been implemented using `ByFrameRepeater`, and the approach was based on reusing panel instances to prevent unnecessary work and, in particular, flickering while writing.
Additionally, adds a `SearchInput` component with some basic behaviors to share in other places where we want a filter.
Demo:
https://github.com/grafana/explore-logs/assets/1069378/60a1ffed-d07a-4b6b-9322-187c35978e71
=> Fields breakdown: add value filter

src/Components/IndexScene/IndexScene.tsx, src/Components/IndexScene/LayoutScene.tsx, tests/exploreServicesBreakDown.spec.ts
It's not pretty, but it works...
Hiding the operator for `service_name`, as this one should always be an `equal` operator.
=> fix(service-name-op): hide operator on `service_name`

src/Components/ServiceScene/LogsListScene.tsx, tests/exploreServicesBreakDown.spec.ts
Fixes https://github.com/grafana/explore-logs/issues/475
Note:
While this works, it's pretty hacky targeting panel internals, and using internal css class suffix isn't great.
=> Logs panel: overflow fix

src/Components/IndexScene/GiveFeedbackButton.tsx, src/Components/IndexScene/LayoutScene.tsx, src/Components/ServiceScene/ServiceScene.tsx
Fixes https://github.com/grafana/explore-logs/issues/448
Adjusting gaps and margins in the top part. Additionally, preventing the `give feedback` button from wrapping.
https://github.com/grafana/explore-logs/assets/1069378/299d7a8a-c1a7-455a-a705-c9a6ab93de4c
=> Header: tighten top space

src/Components/Table/Table.tsx
Quick fix: Making sure we re-calculate widths when window width changes. I can only reproduce the bug with legacy dataplane frames for some reason, in this case the frames are always calculating the width at 0 of the table, resulting in negative numbers in the columns which prevents them from rendering on initial page load.
=> fix(table): fix negative width columns bug

playwright.config.ts, src/services/testIds.ts, tests/exploreServicesBreakDown.spec.ts
Increasing expect timeout, some loki queries were taking longer then 5s locally, I assume this might be responsible for some of the flake in CI as well.
Also adding an assertion in a test that the loading state is undefined before opening the logs panel, were some executions that would run before the dataframe came back.
=> E2E: reduce test flake

.github/workflows/publish-technical-documentation-next.yml
We can test and evaluate the Continuous Delivery of documentation to the website repository without publishing it on the website thanks to https://github.com/grafana/website/pull/20393/files which tells Hugo not to render or list any pages under content/docs/explore-logs/.
We can also put in place a similar workflow for publishing versioned releases of documentation after we decide on how those are going to be maintained. `grafana/grafana` uses long-lived version branches for each version and documentation is synced from those branches. `grafana/k6-docs` doesn't need to version documentation alongside the code (because it's a separate repository) and maintains all of its documentation in the `main` branch.
=> Add workflow that syncs documentation to the website repository on pushes to main

.github/workflows/update-make-docs.yml, docs/Makefile, docs/docs.mk, docs/make-docs, docs/variables.mk
Add the tooling for rendering a local preview of the documentation and a procedure to keep it up to date.
For more information, refer to https://grafana.com/docs/writers-toolkit/review/.
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
=> Add make docs procedure

src/Components/ServiceScene/Breakdowns/FieldSelector.tsx
Just a small helper in the UI to let users know they can search by label name.
Main:
This PR:
This PR:
We don't have a lot of flexibility with the search icon already in the base select component, I would like to always show the search icon so users know it's searchable and not just a dropdown. This PR suggests adding the search icon as a prefix that is only visible when the select isn't open.
Also making the dropdown a bit bigger, the ALL value is selected by default and it's easy to miss this element in this state.
Main:
This PR:
=> UX: add search icon to field/label autocomplete dropdown

README.md, src/Components/Pages.tsx, src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/Components/Table/TableTypes.ts, src/services/testIds.ts, tests/exploreServicesBreakDown.spec.ts
This PR renames all occurrences of `Detected Fields` to `Fields`. Especially with structured metadata this will tab will not only serve "detected" fields, but also structured metadata.
=> chore: rename `Detected Fields` to `Fields`

src/plugin.json
FYI, as discussed, this will auto enable the plugin once installed.
https://grafana.com/developers/plugin-tools/reference/plugin-json#:~:text=supports%20annotation%20queries.-,autoEnabled,-boolean
=> chore: autoenable plugin when installed

src/Components/IndexScene/IndexScene.tsx
With this PR the default datasource will be the datasource with the `grafanacloud-logs` uid. This `uid` is set for the stack's default logs datasource.
=> feat(initial-datasource): always select `grafanacloud-logs` as the default datasource

jest.config.js, package.json, src/Components/ServiceScene/Breakdowns/ByFrameRepeater.tsx, src/Components/ServiceScene/Breakdowns/SortByScene.test.tsx, src/Components/ServiceScene/Breakdowns/SortByScene.tsx, src/module.ts, src/services/sorting.test.ts, src/services/sorting.ts, webpack.config.ts, yarn.lock
This PR introduces some minor improvements to the sorting options, but the main change is the integration of https://github.com/grafana/augurs .
Changes:
- Added changepoint detection as a sorting option (currently the default option, renamed as "Relevance").
- From the previous list of reducers/sorting options, moved stdDev to the second place and renamed it to "Dispersion".
Demo:
https://github.com/grafana/explore-logs/assets/1069378/50fe77f6-1a5a-4b27-887e-9591907a18be
Currently a work in progress/POC.
=> Value breakdown: refactor sorting options and add changepoint detection sorting

src/services/routing.ts
Links with URL encoded values for e.g. `:service` would get double URL encoded and thus don't match any of our defined routes.
This PR just removes the unnecessary additionally routing.
Fixes #517
=> fix(routing): fix routing with url encoded values

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
Fixes the missing lazy loading in fields and label breakdowns by adding the missing `isLazy` property.
=> fix(lazy-load): add missing `isLazy` prop

src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.tsx
This is mostly for consistency. (We could make the editable by the user in the future)
=> Reduce line limit used for field in patterns to 1k

src/Components/ServiceScene/ServiceScene.tsx
Reverts grafana/explore-logs#525
Hoping to be able to revert https://github.com/grafana/explore-logs/pull/518 after this is reverted.
=> Revert "feat(detected-fields): use `1000` as the `line_limit`"

src/Components/IndexScene/PatternControls.test.tsx, src/Components/ServiceScene/LineFilter.test.tsx
This PR fixes errors that pollute Jest output, such as:
```
console.error
Warning: An update to PatternTag inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
```
=> Tests: fix async updates in tests

.github/workflows/release-main.yml
This will just simplify our release workflows. Currently we use a different workflow, and a different bucket to do our `main` releases. This PR will create a new artefact in the same bucket we use for other deployments.
How those will look in the future after this is merged:
- Versioned release: https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-0.0.13.zip
- Latest versioned release: https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip
- Latest `main` release: https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-main.zip
=> chore(release): use common release workflow for `main` releases

.github/workflows/release-main.yml
Yea, well. 
"Alphanumeric" does not include spaces. Just moving from `id` to `name` now which is fine. Validated the workflow with the [actionlint playground.](https://rhysd.github.io/actionlint/)
=> fix(workflow): remove unsupported characters from workflow id

src/Components/IndexScene/IndexScene.tsx
This PR fixes the behavior that would always default to the `grafanacloud-logs` datasource and would never actually use the datasource saved in localstorage.
=> fix(ds-selection): change precedence of selected datasources

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LazyLoader.tsx, src/Components/ServiceScene/Breakdowns/LazySceneCSSGridItem.tsx
This will hide lazyloaded but hidden fields for now to prevent situations like https://play.grafana.org/a/grafana-lokiexplore-app/explore/service/tempo-distributor/fields?var-fields=&var-filters=service_name%7C%3D%7Ctempo-distributor&var-ds=ddhr3fttaw8aod&var-patterns=&var-lineFilter=&var-logsFormat=%20%7C%20logfmt&mode=service_details&urlColumns=%5B%5D&visualizationType=%22logs%22&var-labelBy=$__all&var-fieldBy=$__all&patterns=%5B%5D
=> feat(lazy-loading): use own implementation of `LazyLoader`

.github/workflows/release-main.yml
This uses the `package-plugin` action, that does not include creating a GitHub release, which currently breaks in our `release-main.yaml` workflow.
=> chore: use `package-plugin` action to not include release steps

.github/workflows/release-main.yml
This PR unifies our release approaches. As tried in https://github.com/grafana/explore-logs/pull/537, with this PR we get the following artefacts:
- Versioned release: https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-0.0.13.zip
- Latest versioned release: https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip
- Latest main release: https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-main.zip
This has been tested on this branch successfully: https://github.com/grafana/explore-logs/actions/runs/9887973044
=> chore(release-main): use new `package-plugin` build action

.github/workflows/release-main.yml
Versions from main used to include the commit hash. Adding this back here.
=> chore(release-main): include commit rev in version

src/Components/Table/LineActionIcons.tsx, src/Components/Table/LogsTableHeader.tsx, src/Components/Table/Table.tsx
Removing the link to log line feature as it's a bit buggy right now.
Revert this out after https://github.com/grafana/explore-logs/pull/568 and the scrollTo bug are fixed.
=> Table: Remove link to log line feature

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/SortByScene.test.tsx, src/Components/ServiceScene/Breakdowns/SortByScene.tsx, src/services/sorting.test.ts, src/services/sorting.ts
Closes https://github.com/grafana/explore-logs/issues/574
- Made select input wider
- Added a "target" for the sorting event (so we know if we sorted fields or labels)
- Updated sorting options and descriptions
Available options:
**Most relevant**: Smart ordering of graphs based on the most significant spikes in the data
**Widest spread**: Sort graphs by deviation from the average value
**Name**: Alphabetical order
**Highest spike**: Show graphs with the highest values first (max)
**Lowest dip**: Show graphs with the smallest values first (min)
**10th %**: 10th percentile value
**25th %**: 25th percentile value
**75th %**: 75th percentile value
**90th %**: 90th percentile value
**99th %**: 99th percentile value
=> Sorting: update options and add alphabetical order

src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.tsx
Especially when there are a lot of patterns and a lot of tokens, the dotted underline is not enough to find those tokens. This PR adds a different background colour to those tokens, and emphasises that on hover.
On hover:
=> feat(pattern-tokens): add better visibility to pattern tokens

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
Quick addition to track sorting preferences, and not only changes to sorting preferences. The idea is to have a sense of that sorting preferences and direction users keep.
=> chore: include sorting preference in breakdown tracking

src/services/analytics.ts, src/services/sorting.ts
Wasm may or may not be supported by the browser. When that happens, fall back to stdDev.
=> Sorting: check for wasm support or use stdDev

docs/sources/_index.md
we say 'Explore Logs documentation' but it's obvious it's documentation.
=> no need to say it's documentation

docs/sources/_index.md, docs/sources/ordering/_index.md
Cleaning up the landing page so that it matches the standard template used by the docs team.  Removed the video from the landing page, because 1) it's already linked on the Get Started page and 2) Landing pages aren't intended to include linked videos or graphics other than product logos.
=> docs: more standardization edits

docs/sources/_index.md, docs/sources/access/_index.md, docs/sources/get-started/_index.md, docs/sources/labels-and-fields/_index.md, docs/sources/ordering/_index.md, docs/sources/patterns/_index.md, docs/sources/troubleshooting/_index.md
Fixes #608 by adding `canonical:` to the metadata and setting to the Grafana URL for search engine optimization.
Also updated some descriptions and page weights.
=> docs: Update metadata with canonical URLs

src/Components/ServiceScene/Breakdowns/BreakdownSearchScene.tsx, src/Components/ServiceScene/Breakdowns/ByFrameRepeater.tsx, src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
Summary of changes:
- Moved the filtering code from `BreakdownSearchScene` to `ByFrameRepeater`.
- Added the previously used filter to `ByFrameRepeater`
- `ByFrameRepeater` if has a filter, applies it after "repeating".
- Added a missing UI state for when there are no values matching your search:
Closes https://github.com/grafana/explore-logs/issues/559
=> Value breakdowns: maintain filters between value changes

src/Components/ServiceScene/Breakdowns/Patterns/PatternsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/Patterns/PatternsNotDetected.tsx
Users have expressed frustration when patterns disappear when looking for non-recent logs.
Let's add a UI state and link to the docs that specify how long patterns are around.
=> Patterns: Show UI message when time range is too old to show patterns

project-words.txt, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/services/scenes.ts
This change looks larger than it is. I moved the `buildLabelsLayout` and `buildLabelValuesLayout` into the class, so I can access a sceneObject from `getExpr`.
In `getExpr` you will find the important change: https://github.com/grafana/explore-logs/compare/svennergr/better-label-queries?expand=1#diff-0c7c5b52164d9762335a7b37b5b4822ed449d0a60ea4dd765c8ee29efad26ae1R367-R390
We now create the stream selector expression in the app, to add filtering for only existing items. To prevent the parser from being added, we check for `fields.length` and only add the parser if we have a fields filter expression.
=> Label queries: remove unneccessary filters and parsers in query expression

src/Components/ServiceScene/ServiceScene.tsx, src/Components/ServiceSelectionScene/SelectServiceButton.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/fields.ts, src/services/variableGetters.ts
There are two sets of extra queries that are being run that this PR attempts to fix.
1. When selecting a service, after updating the services variable, for every SceneQueryRunner loaded in the grid layout, we currently re-query, but add in the selected service, leading to a bunch of queries that return nothing, and look like ```{service_name=`mimir-distributor`, service_name=`just-selected-service`}```. Currently you will get 2 of these queries re-run for every single service that you have scrolled to, sometimes leading to dozens or hundreds queries being blasted out when landing on the ServiceScene
This PR simply clears the body of the service selection scene before navigation, which clears out all of the SceneQueryRunners which would have otherwise re-queried on change of the ad-hoc …
=> Service views: Prevent extra queries

src/Components/IndexScene/IndexScene.tsx, src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx, src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.tsx, src/Components/ServiceScene/LineFilterScene.tsx, src/Components/ServiceScene/LogsListScene.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/Components/ServiceSelectionScene/SelectServiceButton.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/scenes.ts, src/services/variables.ts, tests/exploreServicesBreakDown.spec.ts
A significant portion of the codebase reads or writes to variables. Being a common task, we're now moving that code to specific functions.
This aims to decrease unnecessary duplication and leakage of implementation details between scenes (e.g. having to know the exact class when you're only interested in the value).
=> Variables: move variable lookup to getter functions

src/Components/ServiceScene/LogsVolumePanel.tsx, src/services/analytics.ts
Last week we added filtering support from Logs Volume, but we have no visibility on the usage of this feature.
=> Logs Volume: track filtering interactions

project-words.txt, src/Components/ServiceScene/Breakdowns/SortByScene.tsx, src/module.ts, src/services/sorting.ts
This PR adds outlier detection to sort value breakdowns. It works by using [DBSCAN](https://grafana.com/docs/grafana-cloud/alerting-and-irm/machine-learning/forecasts/outlier-detection/#select-the-detection-algorithm-and-sensitivity) to detect outlying intervals, and sorting by the detected quantity.
Addtionally, we're wrapping all the WASM invocations, logging the errors and falling back to StdDev when it happens.
=> Sorting: add outlier detection as a sorting option

docker-compose.dev.yaml, playwright.config.ts, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/datasource.ts, tests/exploreServices.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/663
Note for reviewers: Needed to use `.*` instead of `.+`. `.+` requires additional chars of context to match. To get around the empty query being `.*.*` I added a replace in the runtime datasource after interpolation to replace `.*.*` with `.+`.
Also added some more e2e test coverage for these cases. 
Also updated the port of the grafana e2e instance because recently I started seeing my local grafana instance instead of the one in the docker container.
=> Service selection scene: get service volume by partial or exact match

package.json, yarn.lock
The `fast-loops` dependency has `CVE-2024-39008`. It is nested in @grafana/data -> react-use, etc. 
For now, we will just manually resolve to the fixed `1.1.4` version.
Also, the `jackspeak` resolution did not seem needed anymore? I could execute tests without a problem.
=> chore(deps): resolve `fast-loops` to `1.1.4` to prevent `CVE-2024-39008` notifications

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/filters.test.ts, src/services/filters.ts, tests/exploreServicesBreakDown.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/676
The same level panel shows up in several different places in the UI. Let's remove them all except the one that's pushed to the top of the label breakdown.
=> Breakdowns: Level, detected level, level_extracted, oh my!

src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx, src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/fields.ts, src/services/levels.test.ts, src/services/levels.ts, src/services/panel.test.ts, src/services/panel.ts
Series visibility + filters state:
https://github.com/user-attachments/assets/e7f0bc6b-07c4-421e-9e0f-e90b3a9d0a01
Fixes https://github.com/grafana/explore-logs/issues/686
Extra/minor changes:
- Renamed functions for consistency with their purpose.
- Renamed variables for readability and consistency with their purpose.
- Fixed typo in function name.
- Used variable getters from variables.ts.
- Added comments to levels functions.
=> Logs volume: Fix active state of series based on the filter's state

src/services/fields.test.ts, src/services/fields.ts
Fixes: https://github.com/grafana/explore-logs/issues/704
Note, this is a shorter-term solution, the implementation of detected_fields returns a parser for each field which can be used to better identify which parser to use.
=> ServiceScene: prevent services with a mix of json and logfmt from request looping

src/Components/ServiceScene/LogsVolumePanel.tsx
With the current implementation, there was the possibility of being locked with a logs volume panel with no data, that will not be updated by changes in the top filters.
https://github.com/user-attachments/assets/f685304d-d311-49f8-b133-776baaac3741
=> LogsVolumePanel: re-run query on filters change

src/Components/IndexScene/IndexScene.tsx, src/services/expressions.ts, src/services/query.test.ts, src/services/query.ts
Aimed to fix https://github.com/grafana/explore-logs/issues/691 , this PR adds support for all fields and labels with multiple values.
Fields demo:
https://github.com/user-attachments/assets/984f4d25-aa11-409b-9e4e-19a708bdf9f1
Labels demo:
https://github.com/user-attachments/assets/cfd97a70-a94e-4901-ac1f-15269ec0fc86
=> Filters: add support for filters with multiple values

src/Components/ServiceScene/Breakdowns/FieldValuesBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/SortByScene.tsx, src/services/fields.ts, src/services/store.ts
Fixes: https://github.com/grafana/explore-logs/issues/499
When sorting by a calc value, we add that to the legend:
If using a non-calc value, the panels show up as they currently do:
Note: this doesn't add the calcs to the single view, 
Also since we renamed the calc values, the names don't line up with what is presented in the legend.
=> Value breakdowns: Add calculated sort

project-words.txt, src/services/fields.test.ts, src/services/fields.ts
The first log of the sample can be anything, and the fact that we're only checking one felt awkward.
Updated the implementation to:
- Check all the lines
- Use JSON.parse() instead of checking the first character, like we do in [LogRowMessage](https://github.com/grafana/grafana/blob/main/public/app/features/logs/components/LogRowMessage.tsx#L72).
- Add both parsers when the type is mixed and not only json
=> Extract parser: update heuristic for mixed logs

docker-compose.dev.yaml
Appears to be breaking e2e tests
=> Sync loki versions in docker-compose.dev.yaml

docker-compose.yaml
Fix the Grafana image tag as the `11.2` tag is not existing:
> Error response from daemon: manifest for grafana/grafana:11.2 not found: manifest unknown: manifest unknown
=> fix: grafana image tag

generator/generator.go, project-words.txt
Adding more test cases for e2e tests and local testing.
* New service (`nginx-json-mixed`) with mix of JSON and logfmt
* 50% of errors (2.5% of all log lines) will log an additional line containing:
* * Stacktrace with newlines
* * field that conflicts with stream selector
* * Common field in logfmt line and json lines
=> generator: add new service with mix of json and logfmt

src/services/levels.test.ts, src/services/levels.ts
Before these changes, selecting "logs" in the Logs Volume panel would result in no data, applying an incorrect filter.
Fixes #746
=> Logs Volume Panel: properly handle "logs" detected level

.github/workflows/ci.yml, docker-compose.dev.yaml, index.d.ts, jest-setup.js, package.json, project-words.txt, src/services/combineResponses.test.ts, src/services/combineResponses.ts, src/services/datasource.ts, src/services/logql.ts, src/services/query.ts, src/services/shardQuerySplitting.test.ts, src/services/shardQuerySplitting.ts, tests/exploreServices.spec.ts, tests/fixtures/explore.ts, tests/matchers.ts, yarn.lock
Query splitting was introduced in Loki to optimize querying for long intervals and high volume of data, dividing a big request into smaller sub-requests, combining and displaying the results as they arrive.
This approach, inspired by the time-based query splitting, takes advantage of the __stream_shard__ internal label, representing how data is spread into different sources that can be queried individually.
The main entry point of this module is runShardSplitQuery(), which prepares the query for execution and passes it to splitQueriesByStreamShard() to begin the querying loop.
splitQueriesByStreamShard() has the following structure:
- Creates and returns an Observable to which the UI will subscribe
- Requests the __stream_shard__ values of the selected service:
- If there are no shard …
=> Shard query splitting: Split queries by stream shards

src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
Currently I see two scrollbars. The inner scroll isn't needed anymore, thus we can remove the "forced" `overflow-y: scroll`.
=> fix(service-selection-scrolling): remove forced overflow scroll

src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.test.tsx, src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.tsx, tests/exploreServicesBreakDown.spec.ts
The query expression used to create pattern-key breakdowns is currently broken and missing the enclosing brackets (`{` and `}`).
=> fix(patterns-breakdown): fix expression to create pattern key breakdown

.github/workflows/publish-technical-documentation-next.yml
Each repository can only have 100 organization secrets and there are now more than 100 in our organization which causes inconsistent behavior.
Some repositories don't have the secrets they need assigned.
These composite actions use secrets stored in Vault that are available to all repositories.
- `publish-technical-documentation-next.yml` has been tested with https://github.com/grafana/writers-toolkit/blob/main/.github/workflows/publish-technical-documentation.yml.
**Special notes for your reviewer**:
There is some copy-paste involved in the creation of these workflows. Please check:
For `publish-technical-documentation-next.yml`:
=> Update workflows to use actions that don't need organization secrets

src/Components/ServiceScene/Breakdowns/ByFrameRepeater.tsx, src/Components/ServiceScene/Breakdowns/FieldValuesBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx
Fix bug in the label values where errors are not being surfaced to users and the loading state is left up indefinitely.
If panels are visible, the error will be surfaced within the viz panel, and as a toast message, if panels are not visible the error will be added to the body and remain visible until the next query response.
=> label values: fix label values stuck in loading state

src/services/logql.ts, src/services/shardQuerySplitting.test.ts, src/services/shardQuerySplitting.ts
Seen in some recent tests in ops, where with filters applied that generated a new stream selector, we were getting all the shard values instead of those that correspond to that particular query.
=> Shard query splitting: send the whole stream selector to fetch shard values

src/services/variables.ts
Fixes: https://github.com/grafana/explore-logs/issues/787
To repro: either add `&page_attr_var_fields=user_id|=|123` to the end of an explore logs url, or create a url on a version of explore logs from before  containing fields from before https://github.com/grafana/explore-logs/pull/736 was merged (e.g. [0.1.3](https://github.com/grafana/explore-logs/releases/tag/v0.1.3))
=> fix: fall back to mixed parser if the field is missing parser in url parameter

src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/variables.ts
Current log counts being displayed are incorrect, the updated sum_over_time query unwrapping by count should return the correct volume counts.
=> Aggregated metrics: Use sum_over_time query for aggregated metric queries

src/services/shardQuerySplitting.test.ts, src/services/shardQuerySplitting.ts
Fixes showing "no data" while streaming.
=> fix(shardQuerySplitting): do not emit empty data

src/services/logger.ts
FetchError is thrown from backendSrv, right now we log an "unknown error" message, and lose needed context on the error object when sending to Faro.
=> Frontend error handling: Better FetchError handling

docs/sources/_index.md, docs/sources/access/_index.md, docs/sources/get-started/_index.md, docs/sources/labels-and-fields/_index.md, docs/sources/ordering/_index.md, docs/sources/patterns/_index.md, docs/sources/troubleshooting/_index.md
I took a pass through the docs today to validate that they matched the UI.
Replaced all the relrefs with full URLs as relrefs are being phased out.
Made a few other small edits and stylistic changes.
=> docs: Copyedit and replacing relrefs

src/services/logger.ts, tests/exploreServices.spec.ts, tests/exploreServicesBreakDown.spec.ts, tests/exploreServicesJsonBreakDown.spec.ts, tests/exploreServicesJsonMixedBreakDown.spec.ts, tests/fixtures/explore.ts
Narrowing each prop individually was cumbersome and not very scalable, this attempts to grab string/numeric/boolean properties from errors that are Records
=> Frontend logging: more generic context

src/services/combineResponses.test.ts, src/services/combineResponses.ts, src/services/shardQuerySplitting.ts
Found while working in grafana/grafana. Main fixes are:
- Improved field comparison, where `undefined === undefined` was causing false positives of existing entries.
- Fixed merging of log frames when they have overlapping or duplicated results.
- Added support for the case where `closestIdx()` returns -1 when the passed array is empty.
- Fixed request retrying, moving clearing the timeout to the correct place.
=> Combine responses: improve merging of duplicated entries

src/Components/ServiceScene/LineFilterScene.tsx, src/Components/ServiceScene/LogsPanelScene.tsx
To decrease the chance of firing a lot of requests while a user is typing:
- Increased debounce time to 1 second.
- Added support for running the query immediately with `Enter` if the user needs it.
=> Line Filter: increase debounce time and add enter support

src/services/shardQuerySplitting.ts
Adding missing unsubscriptions for the ones created on every new query that we execute.
=> Shard query splitting: add missing unsubscriptions

src/services/logql.ts, src/services/shardQuerySplitting.test.ts, src/services/shardQuerySplitting.ts
Data is going to be distributed exponentially in shards, but there is no heuristic that can suggest, based in the shard identifier, what the approximately volume is, so there is no safe way to group shards in a way that prevents querying a huge amount of data. In addition, once the groups have been stablished, other than retrying, there is no way of changing the original group definition, and the query ends up taking a lot of time or failing.
To improve this, a new shard grouping approach has been implemented, where the groups are dynamically generated based on the query execution time that is returned as meta data, with the following method:
Initial group shard: `Math.sqrt(shards.length)`. Square root will be significantly small for low or high number of shards, without being 1 …
=> Shard query splitting: use dynamic grouping

src/services/routing.ts
For label values with slashes, we replace them with dashes, so we need to account for that when we check for the value.
=> fix(routing): check for sluggified value in URL

package.json
Looks like I forgot to specify the base branch: https://bundlewatch.io/#/getting-started/diffing-against-branches-other-than-master
=> Bundlewatch: add main as base branch

src/Components/IndexScene/InterceptBanner.tsx, src/Components/IndexScene/LayoutScene.tsx
Moves the intercept banner into the main `container` so it gets the same margins as the rest of the app.
=> chore(intercept-banner): move into `container`

src/img/custom.d.ts
Fixes error:
```
✖ tsc-files --noEmit:
src/Components/ServiceScene/Breakdowns/AddToExplorationButton.tsx:9:22 - error TS2307: Cannot find module '../../../img/logo.svg' or its corresponding type declarations.
```
=> fix: fix broken tsc-files command

project-words.txt, src/services/shardQuerySplitting.test.ts, src/services/shardQuerySplitting.ts
This PR improves error handling in the shard splitting implementation. This is done by:
- Removing the Streaming state when sharding should stop.
- Assigning the Error state on the merged response.
=> feat(shardSplitting): improve error handling

src/services/combineResponses.test.ts, src/services/combineResponses.ts
This PR adds a performance optimization to the label comparison method, which is a function that gets called very often in the recombination code.
1 minute of profiling
Slightly different method but still comparing label keys.
Start and end of `mergeResponses`
1 minute of profiling
Start and end of `mergeResponses`
=> feat(combineResponses): improve label comparison performance

jest.config.js, package.json, src/module.tsx, src/services/sorting.ts, yarn.lock
This release includes separate entry points for the various
parts of the library, which should reduce the amount of
WebAssembly that needs to be loaded by the user.
It also fixes build warnings related to circular dependencies.
=> chore: bump @bsull/augurs to 0.6.0

src/Components/ServiceScene/Breakdowns/SortByScene.tsx
**What is this feature?**
Just a rename
The slack discussion: https://raintank-corp.slack.com/archives/C0630AYC4SY/p1731012871057899?thread_ts=1730815868.075449&cid=C0630AYC4SY
=> Chore: Rename the sorting option in explore metrics

src/Components/ServiceScene/ActionBarScene.tsx, src/Components/ServiceScene/GoToExploreButton.test.tsx, src/Components/ServiceScene/GoToExploreButton.tsx, src/Components/ServiceScene/LogsListScene.tsx, src/Components/ServiceScene/LogsPanelScene.tsx, src/Components/Table/LogsHeaderActions.tsx, src/services/store.ts, src/services/text.ts
This PR extends the GoToExploreButton to respect the selected displayedFields, visualizationType, and table columns, which was a source of confusion for users switching between apps.
Part of #884
Requires https://github.com/grafana/grafana/pull/96242
=> Go to Explore button: keep visual preferences in Explore link

src/Components/ServiceScene/Breakdowns/AddToExplorationButton.tsx
With multiple investigations having a disabled state doesn't work properly. This PR just removes this state for now.
=> feat(explorations): remove disabled state

src/Components/AppConfig/AppConfig.tsx, src/Components/IndexScene/IndexScene.tsx, src/Components/Pages.tsx, src/Components/ServiceScene/Breakdowns/NumericFilterPopoverScene.tsx, src/Components/ServiceScene/Breakdowns/Patterns/PatternsLogsSampleScene.tsx, src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/services/TagValuesProviders.ts, src/services/shardQuerySplitting.ts
Seeing some errors in faro come back as `console.error: [object Object] [object Object]`, be nice to be able to filter them out easier, and have more context for other errors in the future.
=> chore: cleanup faro error messages

src/Components/Panels/PanelMenu.tsx
Log volume panel is hidden in Firefox. Since it's a single `div`, we can position absolutely, which will fix the bug for now.
Fixes #927
=> fix(firefox-panel-hidden): add position absolute

src/services/panel.ts
Found while testing visible range, it can happen that data frame fields are empty
and we were accessing them by index
, causing errors
Can be reproduced with OPS logs and the following URL state: `/a/grafana-lokiexplore-app/explore/service/loki-distributor/logs?from=2024-11-29T09:26:52.467Z&to=2024-11-29T09:27:43.073Z&var-ds=adygcacqmfabkc&var-filters=service_name%7C%3D%7Cloki%2Fdistributor&var-fields=&var-levels=&patterns=%5B%5D&var-metadata=&var-patterns=&var-lineFilter=&urlColumns=%5B%5D&visualizationType="logs"&displayedFields=%5B%5D`
=> SortLevelTransformation: account for possibly empty fields

package.json, src/Components/ServiceScene/GoToExploreButton.tsx, src/Components/ServiceScene/LogsListScene.tsx, src/Components/Table/Context/TableColumnsContext.tsx, src/reset.d.ts, src/services/logger.ts, src/services/narrowing.test.ts, src/services/narrowing.ts, src/services/store.ts, src/services/variableGetters.ts, yarn.lock
Adding https://www.totaltypescript.com/ts-reset to Explore Logs.
The primary use case is for improved type-safety when dealing with values coming from local storage and when parsing JSON encoded strings. There is also some QoL improvements as well, take a look at the link above for more information.
TL;DR localStorage and JSON.parse now return `unknown` instead of `any`.
This PR implements additional runtime narrowing of types to make sure we're not displaying the wrong data, and malicious actors will have a harder time injecting unexpected data through url parameters or local storage.
=> Chore: Better type safety with ts-reset

src/services/datasource.ts, src/services/datasourceTypes.ts, src/services/query.ts
A placeholder string was introduced when creating queries, which was being sent in queries.
This has been removed, adding a function to clean up trailing commas and spaces in stream selectors, which can break queries.
=> Queries: remove placeholder query and sanitize stream selector

src/Components/Panels/PanelMenu.tsx, src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx, src/services/analytics.ts, src/services/store.ts
Adds a new option for numeric fields to allow users to toggle between histogram and time series visualization types.
Also adds grouping categories to the PanelMenu.
Saves last selection in local storage as default viz for numeric panels.
Without investigations:
Numeric panel:
Regular panel:
Fixes: https://github.com/grafana/explore-logs/issues/923
=> Field labels: histogram option for numeric fields

src/Components/ServiceScene/LogsPanelScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx, src/services/logsFrame.ts, src/services/panel.ts, src/services/routing.ts, src/services/text.ts
This PR integrates infinite scrolling support using the updated Logs Panel, and displays the visible range of logs, using two annotations to show the time of the oldes and newest log in the list.
The visible range of logs will be updated when infinite scroll is used.
Demo:
https://github.com/user-attachments/assets/a446fe5a-6d5d-4f25-adcb-f4292db56f2d
Requires https://github.com/grafana/grafana/pull/97095 for infinite scrolling + updating the visible range when new logs arrive.
Additionally, it fixes sharing link to log lines, which were being stripped from the URL, causing the Logs Panel to not receive the required parameters.
https://github.com/user-attachments/assets/f5ccd353-8e70-4c81-a3e1-39719ff00092
Closes #919
=> LogsVolumePanel: Add infinite scroll for logs and display visible range

src/Components/ServiceScene/BreakdownViews.ts, src/services/labels.ts
Fixes: https://github.com/grafana/explore-logs/issues/934
Notes:
There is a bug with the logs panel and the time series panel, where the tooltip will show in the time series panel when hovering on logs, if the time series graph emitted any hover events before hovering over the logs panel.
I reported it here: https://github.com/grafana/grafana/issues/97600
Table isn't working: 
Looks like there is a bug with sorted tables and the shared crosshair: https://github.com/grafana/grafana/pull/97599
But there is something else going on as well, the tooltips don't show up at all, even though the event is being emitted. 
I'm going to suggest we don't add shared crosshairs for the logs panels and volume panel for now, until those issues above are resolved upstream.
Created …
=> Breakdown panels: Add shared crosshairs

src/Components/ServiceScene/LogOptionsScene.tsx, src/Components/ServiceScene/LogsPanelScene.tsx
This PR adds `prettifyLogMessage` to work in combination with `wrapLogMessage`. When `wrapLogMessage` is enabled, so will be `prettifyLogMessage`, expanding json log lines if there are.
https://github.com/user-attachments/assets/4915d8b2-5745-4319-8937-5f181acafab9
=> Logs Panel: Combine wrapLogMessage with prettifyLogMessage

project-words.txt, src/Components/ServiceScene/LineFilterScene.tsx, src/services/store.ts
Part of: https://github.com/grafana/explore-logs/issues/952
Adds the line filter case sensitivity toggle value to local storage
=> Line filter: add case sensitive line filter state to local storage

src/Components/IndexScene/IndexScene.tsx, src/services/keyboardShortcuts.test.ts, src/services/keyboardShortcuts.ts, src/services/narrowing.ts
Add support for `t c` and `t v` in Explore Logs.
Related: https://github.com/grafana/scenes/pull/999
Also ran into this bug while testing: https://github.com/grafana/grafana/issues/97892
=> Keybindings: support time range copy/paste 

src/Components/IndexScene/IndexScene.tsx, src/Components/ServiceScene/ActionBarScene.tsx, src/Components/ServiceScene/Breakdowns/AddToExplorationButton.tsx, src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.test.tsx, src/Components/ServiceScene/Breakdowns/Patterns/PatternNameLabel.tsx, src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTableScene.tsx, src/Components/ServiceScene/LogsPanelScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/services/TagKeysProviders.ts, src/services/TagValuesProviders.ts, src/services/datasource.test.ts, src/services/datasource.ts, src/services/datasourceTypes.ts, src/services/logql.ts, src/services/lokiQuery.ts, src/services/metadata.ts, src/services/panel.ts, src/services/query.ts, src/services/scenes.ts, src/services/shardQuerySplitting.test.ts, src/services/shardQuerySplitting.ts, tests/exploreServices.spec.ts, tests/exploreServicesBreakDown.spec.ts, tests/fixtures/explore.ts
Fixes: https://github.com/grafana/explore-logs/issues/425
\@TODO:
* ✅  we're running this query on every activation of the ServiceScene, can we only run it when the query/timerange changes or if the current count is undefined?
* ✅  fix e2e assertions now that there's another query in the mix
* ✅  LogsCount needs to sum all infinite scroll pages
* ✅ Custom maxLines support
=> Logs Tab: Show log line count

src/Components/ServiceScene/LogsPanelScene.tsx
Before these changes, the ServiceScene was keeping the original data frame but with mutated fields after merging, so it would have an original length of 1000 but potentially many more field values.
With these changes, the table will have access to the updated data frame.
Without this, paginated results will be lost or not available when switching back and forth from table to logs.
Fixes #966
=> Logs panel: update service data when receiving new logs

src/Components/Panels/PanelMenu.tsx, src/Components/ServiceScene/LogsTableScene.tsx, tests/exploreServicesBreakDown.spec.ts
Opening panel menu was throwing an error in Logs Table because no `VizPanel` ancestor could be found. Interestingly `findObjectOfType` returned a `VizPanel` instance, but `sceneGraph.getAncestor` threw an error.
Change the behavior to always use `sceneGraph.getAncestor` and catch the error in case there's not `VizPanel`.
=> fix(panel-menu): menu throwing error in logs table

src/Components/Panels/PanelMenu.tsx
We used `ADD_TO_INVESTIGATION_MENU_DIVIDER_TEXT` / `Investigations` for the divider and group, which cause React to complain about multiple same keys:
=> fix(panelmenu): `Investigations` causing multiple same keys

src/services/datasource.ts
Optimizes the patterns graph. 
Due to defaulting to no step, graphs can sometimes look very spikey:
while they actually shouldn't be when used with a correct `step`:
=> feat(patterns): use grafana's calculated `interval` as `step`

src/Components/ServiceScene/LogsListScene.tsx, src/Components/ServiceScene/LogsTableScene.tsx, src/Components/Table/Context/TableColumnsContext.tsx, src/Components/Table/RawLogLineText.tsx, src/Components/Table/TableProvider.tsx, src/Components/Table/TableWrap.tsx, src/services/testIds.ts, tests/exploreServicesBreakDown.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/977
=> Table: Show log text not preserved in URL state

src/Components/ServiceScene/LogsTableScene.tsx, src/services/comparison.test.ts, src/services/comparison.ts, tests/exploreServicesBreakDown.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/976
=> Table: Column order not preserved in URL

src/Components/IndexScene/ShareButtonScene.tsx, src/Components/ServiceScene/LogsPanelScene.tsx, src/services/text.ts
Fixes: https://github.com/grafana/explore-logs/issues/986
=> chore: clean up copy texts

src/Components/IndexScene/ShareButtonScene.tsx, src/services/migrations.ts, tests/exploreServicesBreakDown.spec.ts, tests/fixtures/explore.ts
Fixes bug introduced by URLSearchParams which will replace whitespace with `+` instead of `%20`
Fixes bug in line filter migration where escaped chars would not get unescaped.
=> fix: use urlUtil instead of UrlSearchParams

src/services/logsFrame.test.ts, src/services/logsFrame.ts
Just sorting the timeField and not the other fields in a frame will lead to mismatching loglines and timestamps. This PR fixes the behavior by not sorting the timeField values in place.
=> fix(sorting): prevent sorting timeFields in place

generator/main.go
Very small PR to add an optional `-tenant-id` flag on the generator
=> feat: option to send tenant id in generator

src/Components/IndexScene/LayoutScene.tsx
=> chore: move `key` prop of metadata controls

src/Components/IndexScene/IndexScene.tsx, src/Components/IndexScene/ShowLogsButtonScene.tsx, src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx, src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/Components/ServiceSelectionScene/AddLabelToFiltersHeaderActionScene.tsx, src/services/TagKeysProviders.ts, src/services/TagValuesProviders.ts, src/services/extensions/links.test.ts, src/services/extensions/links.ts, src/services/filterTypes.ts, src/services/levels.test.ts, src/services/levels.ts, src/services/logqlMatchers.ts, src/services/operators.ts, src/services/query.test.ts, src/services/query.ts
This PR adds support for all labels in Explore Logs coming from an Explore query.
The ability to write arbitrary regex queries within Explore Logs is not supported yet, but this PR is the first step towards providing support in the UI for adding regex label queries.
Field regex operators are not supported yet, but should be a fast follow.
Fixes: https://github.com/grafana/explore-logs/issues/1008
=> Regex labels: support queries from explore

docker-compose.dev.yaml, tests/appNavigation.spec.ts, tests/exploreServicesBreakDown.spec.ts
The e2e tests started failing on https://github.com/grafana/explore-logs/pull/1013.
This PR includes some cherry-picked commits to fix the tests and aims to restore the tests to working order.
=> chore: fix e2e tests

src/Components/ServiceScene/Breakdowns/Patterns/PatternsBreakdownScene.tsx, tests/exploreServicesBreakDown.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/1005
We've had a few users complain as well in the feedback form that patterns are broken, it's likely that this is because the patterns not configured state is no longer showing.
This PR simply shows the error state if we get an error response from the API, and adds an e2e test to ensure we don't break it again in the future.
=> Patterns: Not configured state not working

src/Components/ServiceScene/LogsVolumePanel.tsx
Adding a collectable from the volume panel would add it with an `undefined` name. This changes the name to default to `level`.
=> fix: add default `level` label name for volume panel in investigations

src/Components/ServiceScene/LogsVolumeActions.tsx
- changes the format of the context hints
- prefixes with the "explorelogs" app identifier
=> fix: adaptive-exemption send app name as part of context

generator/generator.go, generator/log/values.go, tests/exploreServicesBreakDown.spec.ts, tests/fixtures/explore.ts
I made some assumptions about the format and count of pod label values, which were being randomly generated.
Updating the `pod` values for tempo-ingester in the generator to have a more consistent and differentiable value format, so we can assert that metadata regex is working as expected.
=> E2E fix: add more deterministic pod value to generator, update e2e

src/services/datasource.ts, src/services/panel.ts
When the core Logs Panel created a new request for infinite scrolling, the direction was missing, resulting in a query always with `backwards` direction. With the direction applied when creating the query runner, now the panel has that property defined and available when a new request is created for infinite scrolling.
Can be reproduced with `Oldest first` sort order.
Before:
https://github.com/user-attachments/assets/ba851fb0-f3ce-443b-9c3c-cdf18ddbba00
After:
https://github.com/user-attachments/assets/07c00507-f19c-4939-8282-dcb806f31b38
=> Logs: apply query direction in query runner

package.json, yarn.lock
Upgrading scenes to get https://github.com/grafana/scenes/pull/1039 which fixes a bug that prevented panels from being hidden in Firefox.
This is the broken behavior where empty panels are shown, but they should be hidden:
=> chore: upgrade scenes to prevent panels from not being hidden

tests/exploreServices.spec.ts
Fix: `should clear filters and levels when navigating back to previously activated service` e2e test, which appears to attempt to scroll before the panels are rendered
=> E2E: Fix flake - not scrolling

src/Components/Table/ColumnSelection/LogsTableNavField.tsx, src/Components/Table/LogsTableHeader.tsx, tests/exploreServicesBreakDown.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/980
Fixes: https://github.com/grafana/explore-logs/issues/1059
Updated header menu for log line:
After resizing column:
Also moved the column header menu to the right side and converted stuff to IconButtons with tooltips:
=> Table: Hide custom pixel width, surface field menu options in column header

src/Components/ServiceSelectionScene/ServiceSelectionPaginationScene.test.tsx, src/Components/ServiceSelectionScene/ServiceSelectionPaginationScene.tsx
This PR uses the totalCount of values to generate the options for the pagination dropdown, using the total count to determine the amount of options and syncing the visible value to the actual value. For example 60 services will generate 3 options, 40 will generate up to 40, and less than 20 will show the actual number. Internally it still uses the same values, but the visible values change according to the total.
For example:
https://github.com/user-attachments/assets/f8fb84b8-d6d8-4932-bdc4-b07c1f8b3b17
=> Service Selection Pagination: Generate options based on total count

src/Components/ServiceSelectionScene/ServiceSelectionPaginationScene.tsx
When options is empty, the resolved value was undefined causing an error when trying to read `.value`
=> fix(ServiceSelectionPagination): check for undefined in options

src/Components/ServiceScene/LogsPanelError.tsx, src/Components/ServiceScene/LogsPanelScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx, src/services/store.ts
This PR subscribes to the logs query and displays an error component when the log query fails, with the objective of improving how we surface errors to the user, making it clear that the query failed and providing a escape hatch to clear all filters.
Before:
After:
=> Logs Panel: Display error message when logs fail to load

.github/workflows/publish-technical-documentation-next.yml, README.md, docs/README.md, docs/sources/_index.md, docs/sources/access/_index.md, docs/sources/get-started/_index.md, docs/sources/labels-and-fields/_index.md, docs/sources/ordering/_index.md, docs/sources/patterns/_index.md, docs/sources/troubleshooting/_index.md, src/Components/AppConfig/AppConfig.tsx, src/Components/IndexScene/InterceptBanner.tsx, src/Components/Pages.tsx, src/Components/ServiceScene/Breakdowns/AddToInvestigationButton.tsx, src/README.md, src/plugin.json, src/services/TagKeysProviders.ts, src/services/extensions/links.ts, src/services/logqlMatchers.ts, tests/exploreServicesBreakDown.spec.ts
Rename Explore Logs to Grafana Drilldown Logs
=> Grafana Drilldown Logs

src/Components/IndexScene/LevelsVariableScene.tsx, src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx, src/Components/ServiceScene/LogsPanelScene.tsx, src/Components/ServiceScene/LogsTableScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx
Just adding browser history for levels variable, and cleaning things up by subscribing to the filter state change instead of having each upstream trigger the re-render on filter change.
=> Browser history on filter change: Levels variable

src/Components/IndexScene/LevelsVariableScene.tsx, src/Components/IndexScene/LineFilterVariablesScene.tsx, src/Components/IndexScene/PatternControls.tsx, src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx, src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/Patterns/FilterByPatternsButton.tsx, src/Components/ServiceScene/LineFilter/LineFilterScene.tsx, src/Components/ServiceScene/LogsPanelScene.tsx, src/Components/ServiceScene/LogsTableScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx, src/services/navigate.ts
Adding browser history events before setting filters to state, when triggered by a user action.
Note: This doesn't catch changes made directly in the combobox variables, but should cover everything? else: patterns, line filters, ([levels in another PR](https://github.com/grafana/logs-drilldown/pull/1108)), and panel filter buttons.
Related: https://github.com/grafana/logs-drilldown/issues/1109
=> Browser history on filter change

config/loki-config.yaml
Getting this error locally:
```
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (6050583 vs. 4194304)
```
Looks like I attempted to add some Faro logs that were too big for the dev loki. Bumping that up a bit here to ~8MB.
=> chore: increase loki max log length

docs/sources/_index.md, docs/sources/access/_index.md
For https://github.com/grafana/website/issues/24017
Removes all relref shortcodes.
Repository: grafana/logs-drilldown
Website-Pull-Request: https://github.com/grafana/website/pull/24501
=> remove relref shortcodes

src/Components/ServiceScene/LogsPanelError.tsx, src/Components/ServiceScene/LogsPanelScene.tsx, src/services/logsFrame.ts
The current error state can be potentially confusing to the users by not being clear of the underlying situation. With these changes we're making a difference between:
- General query errors
- Response too large
- No data returned.
Error:
No data:
Fixes #1121
=> Logs errors: improve error messages

tests/exploreServicesBreakDown.spec.ts
Looks like https://github.com/grafana/logs-drilldown/pull/1127 introduced some flake in this e2e test, although I'm confused as to how it ever worked, but in all of the failures locally and in CI the new empty logs view was being rendered.
Telling the test to run the logs panel query seems to have fixed it locally.
=> E2E: Address flakey test

src/services/panel.test.ts, src/services/panel.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1144
Also displays "unknown" as the same sort/color as "logs" level
=> feat: add critical/fatal log level

src/Components/Panels/PanelMenu.tsx
Fixes https://github.com/grafana/logs-drilldown/issues/1140.
Adds a condition to check which extensions APIs are available in the current grafana runtime. 
[The new observable APIs are introduced in this PR.](https://github.com/grafana/grafana/pull/103063)
We are planning to phase out `getPluginLinkExtensions()` in G12.
=> PanelMenu: Make extensions compatibly with different Grafana versions

.github/workflows/build-generator.yml, .github/workflows/ci.yml, .github/workflows/is-compatible.yml, .github/workflows/publish-technical-documentation-next.yml, .github/workflows/release-main.yml, .github/workflows/release.yml, .github/workflows/update-make-docs.yml
Update github actions to use sha commits for 🔒 securities! [auto action patcher 🤖 ](https://github.com/grafana/github-action-patcher) from @academo ty.
=> chore: (gh actions) - pin to tag for security

src/services/logqlMatchers.ts
- Applying the same fix as https://github.com/grafana/grafana-adaptivelogs-app/pull/588
Assume the same fix would be beneficial here.
=> fix: parseLabelFilters throw error

src/Components/ServiceScene/ActionBarScene.tsx, src/plugin.json
https://github.com/grafana/grafana/pull/103786 removes `appSidecar` and it's implementation. Followup to remove code that was relying on that.
=> chore: remove `ToolbarExtensionsRenderer`

src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTableScene.tsx
Fixes: https://github.com/grafana/logs-drilldown/issues/1185
Before:
After:
=> Patterns: Percentage in table is relative to current pattern search results

src/Components/IndexScene/LayoutScene.tsx, src/Components/IndexScene/VariableLayoutScene.tsx, src/Components/ServiceSelectionScene/AddLabelToFiltersHeaderActionScene.tsx, src/Components/ServiceSelectionScene/SelectServiceButton.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/testIds.ts, tests/appNavigation.spec.ts, tests/exploreServices.spec.ts, tests/fixtures/explore.ts
Currently it's a bit confusing why there are two buttons in the time series panel, and a "show logs" button in the header.
This PR removes the "show logs" button in the service/label row, and replaces it with an "Include" button that matches the buttons used in the breakdown views.
The header is now "sticky" on the service selection, so the "show logs" CTA is always visible.
Fixes: https://github.com/grafana/logs-drilldown/issues/1161
Note:
Aggregated metrics does not support an entry point with multiple labels, so the old style "show logs" button is still used when active:
=> Service selection: Simplify panel buttons

package.json, src/Components/ServiceScene/Breakdowns/LineFilterInput.tsx, src/Components/ServiceScene/LineFilter/LineFilterEditor.tsx, src/Components/ServiceScene/LineFilter/LineFilterScene.test.tsx, src/Components/ServiceScene/LineFilter/LineFilterScene.tsx, src/services/narrowing.ts, yarn.lock
Fixes: https://github.com/grafana/logs-drilldown/issues/989
Asynchronously loads re2JS package when regex is toggled on line filter inputs in an effort to keep load times down for users that will not add regex line filters.
Displays error message from re2JS in tooltip under the input.
Follow ups:
We could potentially prevent the query from executing when an invalid regex is detected, but this would add a bunch of complexity to this PR, and I wasn't certain that the version of re2 used in Loki would exactly map to the frontend library, and didn't want to risk a regression preventing a user from submitting a query that might work on the backend, but throws an error in the client.
Since Loki will validate the query before executing, preventing queries with invalid regex shouldn't impact …
=> Line filters: Client regex validation

src/Components/ServiceScene/LogsTableScene.tsx, src/Components/Table/constants.ts, src/services/narrowing.ts, tests/exploreServicesBreakDown.spec.ts
- #1126 
- Sync the displayFields with the urlColumns
- e2e test to verify url
https://github.com/user-attachments/assets/cfde05f8-c1a6-4b22-a10e-7933b305cc1c
=> feat: (LogPanelTable) - sync the display fields and urlColumns between the logs panel and table

.github/workflows/ci.yml, .github/workflows/release-main.yml, .github/workflows/release.yml
Fixing template injection errors `zizmor --collect=workflows-only .github/workflows`
```
info[template-injection]: code injection via template expansion
--> .github/workflows/release.yml:46:9
|
46 |         - id: 'create-latest'
|  _________-
47 | |         run: cp ${{ steps.build-release.outputs.archive }} ${{ steps.metadata.outputs.archive }}
| |         ----------------------------------------------------------------------------------------
| |_________|______________________________________________________________________________________|
|           |                                                                                      info: this step
|           info: steps.metadata.outputs.archive may expand into attacker-controllable code
|
= note: audit confidence → Low
```
=> chore(zizmor): update for template-injection

src/services/panel.ts
This is causing that the controls attempt to appear when they're not yet supported, with an underlying Grafana 12.0.0-86995
=> chore: update version check for controls

src/Components/ServiceScene/LogsListScene.tsx
Looks like we removed the line filter accidentally from above the table. Let's add it back!
=> fix(table): missing line filter

src/Components/ServiceScene/Breakdowns/LineFilterInput.tsx, src/Components/ServiceScene/LineFilter/LineFilterEditor.tsx
Looks like with latest Grafana onFocus of the `<Input />` component is no longer firing on focus. 
`onFocusCapture` seems to work
=> fix(line-filters): Expand no longer working.

docs/sources/_index.md, docs/sources/viewing-json-logs/_index.md
Created JSON viewer documentation for Logs Drilldown
What this PR does / why we need it:
Documents the new JSON viewer feature of Logs Drilldown
Which issue(s) this PR fixes:
N/A
Special notes for your reviewer:
Checklist
[x] Reviewed the [CONTRIBUTING.md](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (required)
[x] Documentation added
[x] Tests updated
[x] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
=> docs: JSON viewer documentation

src/README.md
Updates the Grafana version listed in the README
Adds the requirement for Loki version to the README
This is to update what is displayed on the Plugins Page.
=> docs: update the versions in the README

docs/sources/_index.md, docs/sources/access/_index.md, docs/sources/get-started/_index.md, docs/sources/labels-and-fields/_index.md, docs/sources/ordering/_index.md, docs/sources/patterns/_index.md, docs/sources/troubleshooting/_index.md, docs/sources/viewing-json-logs/_index.md
This PR:
Hides the video on the Get Started page as it no longer matches the UI and needs to be updated
Updates the Grafana and Loki minimum requirements
Updates the screenshots (Stored online [here](https://admin.grafana.com/upload/media/docs/explore-logs/))
Updates the navigation (there were still a few instances of Explore > Logs)
Adds more description of the user interface to point out some new features
Reorganizes content on some of the pages.
Removes most of the inline troubleshooting, since Logs Drilldown is now GA.
Fixes assorted typos, formatting errors, etc.
Updates the page weights in preparation for new content that will come in the next PR.
=> docs: Updating screenshots and docs

.github/workflows/release.yml
Preparing to try the new plugin-ci-workflows for release. This disables our old release flow from running by commenting out the release.yml trigger on tag push.
=> chore(plugin-ci-workflows): temporarily disable release.yml

.github/workflows/ci.yml, .github/workflows/pr-ci.yml, .github/workflows/publish.yml, docker-compose.dev.yaml, playwright.config.ts, tests/exploreServices.spec.ts
This PR is officially ready for merging 🥳 
- Here's a successful [job](https://github.com/grafana/logs-drilldown/actions/runs/14886934571?pr=1215) running in 15min. 
- On playwright test failures playwright reports are showing up [example](https://github.com/grafana/logs-drilldown/actions/runs/14886416107)
- Mostly the same as pr-ci.yml
- We still need to create a branch, npm run version, generate changelog
- Trigger is pushing a git tag
- Right now the plugin will be uploaded to GCS for backwards compatibility. Eventually it will just be uploaded to the plugin catalogue and deployment_tools should be updated to provision from the catalog rather than GCS.
- Merge this PR
- Remove old release.yml, ci.yml, drone 
- Delete all old jobs from those pipelines to full delete the files
- Create a …
=> chore: (plugin-ci-workflows) - init vanilla plugin-ci-workflows

.github/workflows/publish.yml
Match the pr-ci.yml and skip the dev image on release.
=> chore(plugin-ci-workflows): playwright skip dev image

docs/sources/_index.md
This PR adds the logs drilldown learning journey to the docs
=> docs: add logs drilldown learning journey to the docs

.github/workflows/format-gh-issues.yml
This gh action was not actually adding the issue labels or project id. Updated permissions to use vault and will try again.
=> chore(gha): add proper permissions to format gh issues

src/Components/Panels/PanelMenu.tsx, src/Components/ServiceScene/Breakdowns/FieldValuesBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LayoutSwitcher.test.tsx, src/Components/ServiceScene/Breakdowns/LayoutSwitcher.tsx, src/Components/ServiceScene/Breakdowns/QueryErrorAlert.tsx, src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx, src/services/analytics.ts, src/services/navigate.ts, src/services/shardQuerySplitting.ts, src/services/store.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1343
https://github.com/user-attachments/assets/06cfe42e-299b-47dc-8996-6791a5e7d0a2
For reviewers:
Sharded results should show partial results in the panel.
When panels with errors are displayed the user can still get to the value breakdown, which will always show an error, however it is still useful for users that have partial sharded results.
=> feat(FieldsBreakdown): Show panels with errors

src/Components/ServiceScene/LogsJsonScene.tsx, tests/exploreServicesJsonBreakDown.spec.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1303
Prevents:
* Race condition when loading json viz and detected_fields call is in flight
* Detected_fields not getting called when cached while navigating from the fields tab to the json viz.
Adding e2e coverage for both of these cases as well.
=> fix(JSON): detected fields not always getting called on activation

.github/workflows/pr-ci.yml
This PR does some changes to the GitHub Actions workflows following some changes in plugin-ci-workflows and Grafana Plugins CD Argo Workflow:
- Updates the push to main workflow to trigger a Grafana Cloud deployment to dev + ops
- Updates the push to main workflow to tell Argo to auto-merge PRs in deployment_tools for dev + ops
**Details:**
After https://github.com/grafana/plugin-ci-workflows/pull/131 and https://github.com/grafana/plugin-ci-workflows/pull/135 and https://github.com/grafana/deployment_tools/pull/287893, the behavior of the `environment` parameter in the cd workflow has changed:
- dev deploys to dev only
- ops deploys to ops only (used to be dev + ops)
- prod deploys to dev + ops + prod
We however introduced support to trigger multiple environments by passing them as a …
=> chore(gha): deploy each commit to dev + ops, auto-merge dev and ops PRs

src/Components/ServiceScene/LogsPanelScene.tsx
Uses details mode for the Logs panel. The other panels default to inline.
Requires https://github.com/grafana/grafana/pull/107902
=> feat(LogsPanel): set details mode

src/services/datasource.ts
We shouldn't ever get more then 100 patterns per hour in the query interval for worst-case behavior when there are no common patterns between logs ingested every hour. 
We should probably follow up and display an unobtrusive warning when the limit is hit, but this will keep crazy queries from crashing the browser until Loki sets a limit on the backend.
Related: https://github.com/grafana/loki/issues/18374
=> fix: limit patterns to 500

project-words.txt, src/plugin.json, src/services/extensions/links.ts
This PR supports https://github.com/grafana/metrics-drilldown/issues/524
Adds `'grafana-metricsdrilldown-app/open-in-logs-drilldown/v1'` as another extension point that can leverage the "Open in Grafana Logs Drilldown" link
On a feature branch in Metrics Drilldown, the extension point is working as expected in the Related Logs tab:
https://github.com/user-attachments/assets/2b98dab1-b7a2-496e-9317-9853659c0e9a
It's tedious to do all of the setup involved in testing that this extension point not only exists, but also achieves the goals described in https://github.com/grafana/metrics-drilldown/issues/524. But if you're feeling brave, the full testing instructions are provided in the **How to test** section of https://github.com/grafana/metrics-drilldown/pull/535.
=> feat: enable Logs Drilldown link in Metrics Drilldown

src/Components/ServiceScene/JSONPanel/JsonRootNodeNavigation.tsx, src/Components/ServiceScene/JSONPanel/LabelRenderer.tsx, src/Components/ServiceScene/JSONPanel/ReRootJSONButton.tsx, src/Components/ServiceScene/LogsJsonScene.tsx
Partially fixes: https://github.com/grafana/logs-drilldown/issues/1396
This PR will at least prevent the bug that requires json logs to change the root node, but doesn't solve this problem if the user is not in the JSON panel when the labels are changed, that is being addressed in https://github.com/grafana/logs-drilldown/pull/1401.
This PR also refactors this component out for potential use in other contexts, and helps pay down some debt in the JSON panel.
=> fix(JSON): Allow changing root if no JSON logs present

docs/sources/get-started/_index.md
I added links to the docs for recent videos I've created on the Grafana YouTube channel about Logs Drilldown in a "Further resources" section.
=> docs: Add links to videos on Logs Drilldown

src/Components/ServiceScene/LogsPanelScene.tsx, src/Components/ServiceScene/LogsVolumePanel.tsx
- No longer passing `displayMode` so it uses the default value or the stored preference (requires https://github.com/grafana/grafana/pull/108065)
- Fixed visible range when Logs Volume was collapsed
- Removed internal data override when new logs are received from infinite scrolling, which was causing a scroll jump in the new panel
Besides these changes, the current behavior should match the behavior in main minus the bugs.
Part of https://github.com/grafana/grafana/issues/99075
https://github.com/user-attachments/assets/a7eb9501-8f47-4f96-90f0-f0bc70d3df1d
https://github.com/user-attachments/assets/cd1a0273-f50d-4a81-8f4e-c2dc3c914bfb
=> fix(LogsPanel): visible range and panel improvements

src/Components/ServiceScene/JSONPanel/ValueRenderer.tsx, src/Components/ServiceScene/LogsJsonScene.tsx, tests/exploreServicesJsonBreakDown.spec.ts
Only calculates line filter matches when highlighting is toggled.
Fixes: https://github.com/grafana/logs-drilldown/issues/1414
=> chore(JSON): only calculate line filter matches if highlighting is enabled

.eslintignore, docker-compose.local.yaml, src/Components/ServiceScene/LogListControls.tsx, src/Components/ServiceScene/LogsTableScene.tsx, src/Components/Table/LogLineCellComponent.tsx, src/Components/Table/LogsTableHeader.tsx, src/Components/Table/LogsTableHeaderWrap.tsx, src/Components/Table/Table.tsx
- #1399  
- Disable the labels/show raw log line button if the Log Line column is not visualized.
https://github.com/user-attachments/assets/208be83d-5849-447e-8728-a1978aca7d7e
- Updated the Column width estimator isn't taking the new icons into effect. Also removed columns from the columnWidthMap on hide. Not sure we want that change, but it took me a while to realize that was skipping the `getInitialFieldWidth` function.
=> feat(table): column width estimator and toggle logsPanelControls

.github/workflows/pr-ci.yml, docker-compose.local.yaml, docker-compose.yaml, tests/exploreServices.spec.ts, tests/exploreServicesBreakDown.spec.ts, tests/fixtures/explore.ts
Fixing testids that changed in core.
Skipping tests that touch the logs panel options as the new `logsPanelControls` is default as of the new Grafana release.
=> test(e2e): fix e2e

.github/workflows/conventional-commits.yml, .versionrc.js, commitlint.config.js, src/Components/IndexScene/ToolbarScene.tsx, src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/lokiQuery.ts
The Service Selection scene has logic to reuse existing panels, which was causing panels to be reused when switching data sources, which had the unintended consequence of not updating them when the data source changes. https://github.com/grafana/logs-drilldown/blob/main/src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx#L948
Example:
https://github.com/user-attachments/assets/743c4d92-d938-4e30-9485-b8b922ba113d
After these changes, we'll reset the layout when the data source is changed.
Additionally:
- The "splitDuration" experimental attribute has been removed.
- Fixed non-nullish conditional.
- Reverted [conventional commits change](https://github.com/grafana/logs-drilldown/pull/1442) preventing commits and failing in CI.
=> fix(ServiceSelection): reset service selection after changing data source

package.json, src/Components/IndexScene/IndexScene.tsx, src/services/assistant.test.ts, src/services/assistant.ts, yarn.lock
This pull request introduces updates to integrate into the Grafana Assistant plugin. It uses `@grafana/assistant`'s `providePageContext` method to automatically provide the selected data source and selected label selectors in the Assistant's context:
https://github.com/user-attachments/assets/543ff874-2e41-4cdb-9ab6-e6ebbe3b8a67
=> feat(assistant-context): provide datasource and labels as context to Assistant

docker-compose-syslog.dev.yaml, docker-compose.dev.yaml, docker-compose.local.yaml, docker-compose.yaml, src/Components/ServiceScene/Breakdowns/Patterns/PatternsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/Patterns/PatternsFrameScene.tsx, src/Components/ServiceScene/Breakdowns/Patterns/PatternsViewTableScene.tsx, src/Components/ServiceScene/ServiceScene.tsx, src/services/datasource.test.ts, src/services/datasource.ts, src/services/panel.ts, tests/exploreServicesBreakDown.spec.ts
Merges patterns with the same pattern name.
Fixes: https://github.com/grafana/logs-drilldown/issues/1457
Also fixes a bug where the pattern count can be incorrect if a pattern contains multiple levels.
Notes for reviewers:
You must re-run `yarn server` to see levels on the pattern responses.
=> feat(Patterns): filter by level

src/Components/IndexScene/VariableLayoutScene.tsx
Since the header height in Grafana can change depending on the state of sidebar apps like investigations or assistant, we need to pull the top offset from Grafana instead of hardcoding for fixed/sticky postion headers.
=> fix(ServiceSelection): header offset conflict with sidebar apps

src/services/panel.ts, src/services/shardQuerySplitting.ts
Before some recent Loki changes, max series reached was triggering an error response. Now, it changed to return partial data and a notice. That caused sharding to continue querying, which not only was unnecessary, but caused lag by trying to merge many many series in the frontend.
=> fix(shardQuerySplitting): stop when hitting max series

src/Components/IndexScene/IndexScene.tsx, src/Components/Panels/PanelMenu.tsx
Looks like https://github.com/grafana/logs-drilldown/pull/1426 introduced a regression for users running Grafana 11.6.
The `isAssistantAvailable` method calls `getObservablePluginLinks` which does not exist in grafana <12.
@svennergr when you get back in the office I would appreciate it if y'all could clean up the `isAssistantAvailable` method to support being called in plugins that support older versions of Grafana then the assistant app does.
=> fix: prevent runtime error in Grafana 11.6 from crashing in Drilldown 1.0.24

package.json, src/Components/IndexScene/IndexScene.tsx, src/Components/Panels/PanelMenu.tsx, yarn.lock
https://github.com/grafana/grafana-assistant-app/pull/1239 moved the `getObservablePluginLinks` check into the SDK itself, which will make the `getObservablePluginLinks` check in Logs Drilldown unnecessary. 
Thanks for catching that @gtk-grafana! Feel free to keep it here, if you want. Just wanted to offer using the new version of `@grafana/assistant`.
Btw, have you thought about running e2e tests in CI against the earliest supported Grafana version?
=> fix(assistant): move `getObservablePluginLinks` check to `@grafana/assistant` package

src/Components/EmbeddedLogsExploration/EmbeddedLogs.tsx, src/services/metadata.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1324
This might be our first known bug that exists in an embedded context but is only reproducible in an embedded app that conditionally renders the app with different props. TL;DR this is not currently testable in our embedded e2e route. Although it sounds like there is some upcoming work on better testing Grafana with bundled plugins, so that might change in the future.
Note: We could put in some effort to build a meta-UI within the embedded route that allows users to customize the input props, if this were a more significant change I would suggest it, but I think we're fine to let it slide for now.
=> fix(embedded): force metadata reset on init

src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx, src/services/store.ts
This PR reverts the integration of displayed fields in the Service Selection page from https://github.com/grafana/logs-drilldown/pull/1456 . 
There are many situations where the field can be missing during service selection, such as the case for parsed fields, resulting in empty panels or missing values.
If we're required to support this in the future, we can come back to this and introduce parsers to the landing page, which is not expected for now.
=> fix(ServiceSelectionScene): roll back showing stored displayed fields

src/Components/ServiceScene/LineFilter/LineFilterEditor.tsx
Tiny follow up to https://github.com/grafana/logs-drilldown/pull/1538 , where I noticed the following:
=> chore(LineFilter): increase default width to accommodate for placeholder

src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx, src/Components/ServiceScene/Breakdowns/NoMatchingLabelsScene.tsx, src/services/variableHelpers.ts, tests/exploreServicesBreakDown.spec.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1566
If there are any variables that can be cleared we should be showing the "clear variables" button instead of the empty state UI.
=> fix: unexpected clear variable behavior
