grafana/logs-drilldown

- src/components/Explore/LogsByService/Tabs/FieldsBreakdownScene.tsx
- src/components/Table/DefaultCellComponent.tsx
- src/components/Table/DefaultPill.tsx
- src/components/Table/LineActionIcons.tsx
- src/components/Table/LogLineCellComponent.tsx
- src/components/Table/LogsTableHeader.tsx
- src/components/Table/LogsTableHeaderWrap.tsx
- src/components/Table/Table.tsx
> Table: Move line actions to first field

- .husky/commit-msg
- .husky/pre-commit
- .lintstagedrc.js
- commitlint.config.js
- package.json
- yarn.lock
- Add Conventional commits
- Add Prettier hook
> chore: commit lint, prettier

- src/Components/GrotError.test.tsx
- src/Components/GrotError.tsx
- src/Components/Index/ServiceSelectionComponent.tsx
- src/Components/Tabs/Patterns/PatternsScene.tsx
- #246 
- lmk if there is better copy for this 😉
> feat: volume 404 grot error

- tests/exploreServicesBreakDown.spec.ts
Adding a few more tests for patterns, detect labels, and updating a filter.
> chore: e2e tests for filters, pattern, detected fields

- src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
- src/Components/ServiceScene/ServiceScene.tsx
- src/services/scenes.ts
Follow up of https://github.com/grafana/explore-logs/pull/301
> Chore: rename function and remove duplicated code

- src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
- src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
- src/Components/ServiceScene/Breakdowns/LabelBreakdownScene.tsx
- src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx
- src/services/fields.ts
Renaming `AddToFiltersGraphAction` to `AddToFiltersButton` to match the filename.
> chore: rename `AddToFiltersGraphAction` to `AddToFiltersButton`

- src/Components/IndexScene/IndexScene.tsx
Fixes: https://github.com/grafana/explore-logs/issues/306
Fixes: https://github.com/grafana/explore-logs/issues/314
> feat(preview badge): add preview badge

- .github/workflows/ci.yml
- playwright.config.ts
- src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx
- src/Components/ServiceScene/ServiceScene.tsx
- tests/exploreServicesBreakDown.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/331
Ran into some trouble with the test data, so I also added the video upload and attached the e2e report in ci to match what the platform team is suggesting: https://grafana.com/developers/plugin-tools/e2e-test-a-plugin/ci
> fix(patterns): lazy load pattern timeseries

- src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
Fixes https://github.com/grafana/explore-logs/issues/207
> feat(serviceIndex): add crosshair sync to panels within service index

- src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx
- src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Part of https://github.com/grafana/explore-logs/issues/354
> chore: remove redundant titles

- src/services/analytics.ts
We can decide in the future if we want to continue with this, but wanted to document for @zizzpudding and @stevendungan what props/columns are we currently tracking with these events.
> chore: document props in analytics

- src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Fixes: https://github.com/grafana/explore-logs/issues/384
> chore(patterns): remove pointer events

- src/Components/ServiceScene/Breakdowns/PatternsViewTableScene.tsx
Fixes: https://github.com/grafana/explore-logs/issues/382
> chore(patterns): update percent column to include total count

- src/Components/ServiceScene/LineFilter.tsx
> fix(line-filter): fix search input including regex

- src/Components/Table/Table.tsx
Default sort by time in table viz.
> Table UI: Default sort

- src/Components/GrotError.tsx
- src/Components/ServiceScene/Breakdowns/PatternsBreakdownScene.tsx
> tweaked 'no patterns' text (untested)

- src/Components/ServiceScene/LogsTableScene.tsx
- src/Components/Table/Context/QueryContext.tsx
- src/Components/Table/TableProvider.tsx
Fixes: https://github.com/grafana/explore-logs/issues/443
Also removed unused filters from QueryContext, we might want to add them back in when negative filters are supported to prevent people from seeing the context menu item to add a filter that's already been added.
> Bug: Table - Add indexed labels to stream selector

- src/Components/Table/CellContextMenu.tsx
Waiting for @ivanahuckova's changes on negative filtering in the UI, but it should work out of the box 🤞
> Table UI: re-enable negative filters

- package.json
> Release 0.0.13

- CHANGELOG.md
- README.md
- src/README.md
- src/plugin.json
Some minor doc updates to the plugin installation page which is pretty bare right now.
Updating the Grafana dependency version, which currently points to a version that won't work.
> Docs & dependency updates

- src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
> Service selection: escape service in volume query

- src/Components/ServiceScene/Breakdowns/SortByScene.test.tsx
- src/Components/ServiceScene/Breakdowns/SortByScene.tsx
Copy update for the default method.
> Sort: update default sorting method name and description

- .github/workflows/release-main.yml
> fix(workflow): remove unsupported characters from workflow id

- docs/sources/access/_index.md
fixed troubleshooting link on access page
> fixed broken link

- docs/sources/access/_index.md
- docs/sources/get-started/_index.md
- docs/sources/patterns/_index.md
- docs/sources/troubleshooting/_index.md
https://docs.google.com/document/d/13hUp_8VLayNbcfbGQcFeanLbjDv-VKN8WSP0IePJFwY/edit
> Final docs tweaks

- docs/sources/access/_index.md
Fix heading levels in Installation topic.
> docs: Fix heading levels

- README.md
there's a simpler URL for accessing docs: https://grafana.com/docs/grafana/latest/explore/simplified-exploration/logs/
> Docs update docs link

- src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
Introduced by refactoring due to label value routes.
> Fields: fix loading forever when fields return empty

- src/Components/IndexScene/IndexScene.tsx
- src/Components/ServiceScene/Breakdowns/FieldsBreakdownScene.tsx
- src/Components/ServiceScene/LogsListScene.tsx
- src/Components/ServiceScene/ServiceScene.tsx
- src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
Fixes: https://github.com/grafana/explore-logs/issues/616
> Chore: Clean up subscriptions

- package.json
- yarn.lock
New version. Will enable new ML for the near future, and improve the changepoint performance.
> chore: upgrade augurs

- project-words.txt
- src/Components/ServiceScene/Breakdowns/FieldSelector.test.tsx
- src/Components/ServiceScene/Breakdowns/FieldSelector.tsx
Fixes: https://github.com/grafana/explore-logs/issues/660
And add some simple tests in case I break it again with a bad merge :/
> Service selection: Custom filter value UI broken

- src/Components/ServiceScene/ServiceScene.tsx
- tests/exploreServices.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/657
> ServiceScene: Fix invalid queries being called when navigating to service selection

- src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
- src/services/query.ts
Fixes: https://github.com/grafana/explore-logs/issues/662
> Service selection: Results shown from wrong datasource after switching

- docs/sources/_index.md
Via docs shortcode, we can give users the opportunity to directly play with and inspect the feature on Grafana Play
> add play link to demonstrate product

- src/Components/ServiceScene/Breakdowns/Patterns/PatternsFrameScene.tsx
- tests/exploreServicesBreakDown.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/698
> Patterns: Legend selection not working

- src/Components/IndexScene/IndexScene.tsx
- src/Components/ServiceScene/ServiceScene.tsx
- src/services/variables.ts
- tests/appNavigation.spec.ts
- tests/exploreServices.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/683
> ServiceScenes: Detected level variable not clearing after changing service

- docs/sources/access/_index.md
Fixes: https://github.com/grafana/explore-logs/issues/701
> fix: bad links

- config/loki-config.yaml
- docker-compose.yaml
Upgrades the loki and loki-config used in both compose files to be one that has support for aggregated metrics.
> chore: upgrade compose loki to enable aggregated metrics

- src/Components/ServiceScene/Breakdowns/SortByScene.tsx
Quick win!
Fixes: https://github.com/grafana/explore-logs/issues/721
> Value breakdowns: Add volume sort

- src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
- src/services/datasource.ts
- tests/exploreServices.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/727
> Service selection: limit number of services rendered in service selection

- CHANGELOG.md
- cspell.config.json
- docker-compose.yaml
- package.json
- src/plugin.json
- tests/exploreServicesBreakDown.spec.ts
* Bumped version to 0.1.3
* Updated Grafana dependency to 11.2
* Updated changelog for 0.1.2 and 0.1.3
> release 0.1.3

- src/Components/IndexScene/GiveFeedbackButton.tsx
Fixes: https://github.com/grafana/explore-logs/issues/775
> GA: remove preview badge

- src/Components/IndexScene/InterceptBanner.tsx
Fixes: https://github.com/grafana/explore-logs/issues/776
> GA: Remove preview copy in intercept banner

- docs/sources/_index.md
- docs/sources/access/_index.md
- docs/sources/get-started/_index.md
- docs/sources/labels-and-fields/_index.md
- docs/sources/ordering/_index.md
- docs/sources/patterns/_index.md
- docs/sources/troubleshooting/_index.md
* removed preview warning banner
* updated copy and added support links
> removed preview warning and updated some copy (added link to support)

- src/services/logger.ts
- tsconfig.json
Also update rootdir so we can import files outside src without compiler errors
> Logging: Add plugin version to context

- docs/sources/access/_index.md
Update the installation instructions to include the need to enable structured metadata.
> docs: update installation instructions

- src/services/shardQuerySplitting.ts
Seen in grafana/grafana in the time query splitting with retrying support. This change indicates that the request will be retried so `.complete()` doesn't trigger the next request.
> Shard query splitting: add retrying flag to prevent cancelled requests

- src/Components/ServiceScene/Breakdowns/Patterns/PatternsBreakdownScene.tsx
Fixes: https://github.com/grafana/explore-logs/issues/832
> Patterns: fix flashing no patterns UI when loading

- src/Components/ServiceScene/ServiceScene.tsx
- tests/exploreServices.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/844
> Breakdowns: Changing primary label doesn't update tab count

- project-words.txt
- src/Components/ServiceScene/CopyLinkButton.test.tsx
- src/Components/ServiceScene/CopyLinkButton.tsx
- src/Components/ServiceScene/LogsPanelScene.tsx
- src/Components/Table/LineActionIcons.tsx
- src/services/text.ts
Requires https://github.com/grafana/grafana/pull/95330
This PR adds support for linking to log lines from the logs viz.
Closes #772
> Logs panel: add button to copy link to log line

- src/Components/IndexScene/IndexScene.tsx
Fixes: https://github.com/grafana/explore-logs/issues/876
> fix: console error when undefined jsondata.interval

- package.json
- yarn.lock
https://osv.dev/vulnerability/GHSA-4vvj-4cpr-p986
> Webpack: upgrade to 5.95

- src/Components/ServiceScene/LogsVolumePanel.tsx
Fixes https://github.com/grafana/explore-logs/issues/953
https://github.com/user-attachments/assets/450debc4-81ea-4a67-b9a0-f1964812d22f
> fix(LogsVolumePanel): fix display of visible range when using cached data

- src/Components/Table/TableProvider.tsx
- src/Components/Table/TableWrap.tsx
- yarn.lock
Fixes: https://github.com/grafana/explore-logs/issues/981
> chore: run `yarn audit fix`

- package.json
- src/Components/IndexScene/LineFilterVariablesScene.tsx
- src/Components/ServiceScene/LineFilter/LineFilterCaseSensitivityButton.tsx
- src/Components/ServiceScene/LineFilter/LineFilterEditor.tsx
- src/Components/ServiceScene/LineFilter/LineFilterScene.test.tsx
- src/Components/ServiceScene/LineFilter/LineFilterScene.tsx
- src/Components/ServiceScene/LogsPanelScene.tsx
- src/services/extensions/links.test.ts
- src/services/extensions/links.ts
- src/services/filterTypes.ts
- src/services/logqlMatchers.ts
- src/services/migrations.ts
- src/services/query.test.ts
- src/services/query.ts
- tests/exploreServicesBreakDown.spec.ts
- yarn.lock
Pull line filters from link extension queries into explore logs.
Note: Updates scenes to 5.37.0
> Link extensions: Add support for line filters

- src/services/query.test.ts
- src/services/query.ts
Fixes: https://github.com/grafana/explore-logs/issues/1002
> Patterns: patterns containing quotes break when added as filter

- src/services/query.test.ts
- src/services/query.ts
- tests/appNavigation.spec.ts
- tests/exploreServices.spec.ts
Fixes: https://github.com/grafana/explore-logs/issues/1011
> Service selection: make volume search case-insensitive

- src/Components/ServiceScene/GoToExploreButton.test.tsx
- src/Components/ServiceScene/GoToExploreButton.tsx
Fixes: https://github.com/grafana/explore-logs/issues/1017
> Table: Open in Explore links do not add labelFieldName

- project-words.txt
How did someone merge to main without running the ci test-pr?
> chore: fix spellcheck

- src/Components/ServiceScene/LogsVolumePanel.tsx
- src/services/panel.ts
Fixes: https://github.com/grafana/explore-logs/issues/1039
> LogsVolume: Set axis soft min of 0

- src/services/TagValuesProviders.test.ts
- src/services/TagValuesProviders.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1087
> Labels combobox: Cannot add more then 2 values for same label

- src/Components/OpenInLogsDrilldownButton/OpenInLogsDrilldownButton.test.tsx
- src/Components/OpenInLogsDrilldownButton/OpenInLogsDrilldownButton.tsx
- src/Components/OpenInLogsDrilldownButton/types.ts
- src/plugin.json
- src/services/extensions/exposedComponents.tsx
Forgot to rename the exposed component - probably because it was merged later.
> chore(rename): rename exposed component

- src/Components/ServiceSelectionScene/ServiceSelectionTabsScene.tsx
Fixes: https://github.com/grafana/logs-drilldown/issues/1095
> fix: add overflow-y to tabs container

- src/Components/IndexScene/LevelsVariableScene.tsx
- src/Components/ServiceScene/Breakdowns/LabelValuesBreakdownScene.tsx
- src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
- src/Components/ServiceScene/LogsPanelScene.tsx
- src/Components/ServiceScene/LogsTableScene.tsx
Fixes: https://github.com/grafana/logs-drilldown/issues/1096
> fix: clear filters icon not working with detected_level

- src/Components/IndexScene/ShowLogsButtonScene.tsx
- src/Components/ServiceScene/ActionBarScene.tsx
- src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
- src/Components/ServiceScene/ServiceScene.tsx
- src/Components/ServiceSelectionScene/SelectServiceButton.tsx
- src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
- src/services/navigate.test.ts
- src/services/navigate.ts
- tests/appNavigation.spec.ts
- tests/exploreServices.spec.ts
- tests/exploreServicesBreakDown.spec.ts
- tests/exploreServicesJsonBreakDown.spec.ts
- tests/exploreServicesJsonMixedBreakDown.spec.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/822
Replaces onClick navigation handlers on buttons and drilldown tabs with anchor tags.
> Navigation: Links

- src/Components/ServiceScene/ActionBarScene.tsx
> Share Button: move share button to right side on small viewports

- src/services/extensions/links.test.ts
- src/services/extensions/links.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1110
> fix: empty label values missing labelValues

- src/Components/IndexScene/LineFilterVariable.tsx
- src/Components/IndexScene/LineFilterVariablesScene.tsx
- src/Components/ServiceScene/Breakdowns/LineFilterInput.tsx
- src/Components/ServiceScene/LineFilter/LineFilterEditor.tsx
- src/Components/ServiceScene/LineFilter/LineFilterScene.tsx
- tests/exploreServicesBreakDown.spec.ts
Expands line filter inputs depending on content length.
Fixes: https://github.com/grafana/logs-drilldown/issues/1048
https://github.com/user-attachments/assets/a9a0dfbe-3571-4ae4-88aa-4a6795a74e12
> Line filters: Expand on focus

- README.md
- src/README.md
- src/plugin.json
👋 After the discussion, we are updating description to match the documentation https://grafana.com/docs/grafana/latest/explore/simplified-exploration/
> Update app description

- src/Components/ServiceScene/LogsPanelScene.tsx
Failed to push https://github.com/grafana/logs-drilldown/pull/1127/files#r2002660839
> Logs panel: log errors

- src/Components/ServiceScene/LogsPanelScene.tsx
Follow up of https://github.com/grafana/logs-drilldown/pull/1128
> Logs Panel: Add metadata to logged error

- README.md
Fixes: https://github.com/grafana/logs-drilldown/issues/1142
> Docs: update readme to include discover_log_levels config requirement

- src/Components/ServiceSelectionScene/ServiceSelectionScene.tsx
- src/services/lokiQuery.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1141
> Label selection: set step as 10s for aggregated metric queries

- src/services/query.test.ts
- src/services/query.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1152
> Line filter: Fix error being thrown when toggling case sensitivity with empty value

- src/Components/Panels/PanelMenu.tsx
https://github.com/grafana/metrics-drilldown/pull/232#issuecomment-2775893581
> fix(investigation): links should use `firstValueFrom`

- package.json
- src/Components/ServiceScene/Breakdowns/LayoutSwitcher.test.tsx
- src/Components/ServiceScene/Breakdowns/LayoutSwitcher.tsx
- src/services/store.ts
- #694 
- This became surprisingly easy once I found LayoutSwitcher.tsx and remember classes. Let me know if this is too easy and I'm missing something!
https://github.com/user-attachments/assets/bd0b2641-ce34-4b25-b8ff-7be9d8c4ca2e
> feat: (layoutSwitcher) - set layoutSwitcher from localStorage

- .env.template
- .gitignore
- docker-compose.local.yaml
- provisioning/datasources/default.yaml
Provision loki-dev-005 and add `.env.template` file. 
Are there internal docs I should update? 🤔
> chore: (provisioning) - add loki datasource and env

- src/Components/ServiceScene/LogsJsonScene.tsx
Set show menu always in json viz
> Fix: JSON viz panel menu visibility

- .github/workflows/ci.yml
- docker-compose.dev.yaml
- docker-compose.local.yaml
- docker-compose.yaml
- generator/Dockerfile
- generator/flog/log.go
- generator/flog/random.go
- generator/generator.go
- generator/log/otel-logger.go
- generator/main.go
- generator/otel-config.yaml
- project-words.txt
- tests/exploreServices.spec.ts
This PR adds some new generators I need for the Grafanacon talk, as well as fixes up a few things with our existing generators, such as
1. correct handling of OTEL resource attributes (ie. cluster, namespace, and env)
2. fix `bytes` detection by adding a unit
3. add a `msg` field to json logs for pattern detection
> Otel generator changes

- .github/workflows/conventional-commits.yml
Stolen from @trevorwhitney 😎 & loki
> chore(gh actions): check pr titles for conventional commits

- src/Components/ServiceScene/Breakdowns/FieldsAggregatedBreakdownScene.tsx
- src/Components/ServiceScene/Breakdowns/NumericFilterPopoverScene.tsx
- src/Components/ServiceScene/Breakdowns/SelectLabelActionScene.tsx
- tests/exploreServicesBreakDown.spec.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1225
Adds support for numeric operators on int fields
> feat: support numeric operators for int fields

- generator/flog/log.go
A few small fixes for the grafanacon talk, thanks!
> chore: update generated shopping cart logs

- project-words.txt
- src/Components/IndexScene/ToolbarScene.tsx
Fixes bug making aggregated metric dropdown unclickable
> fix(aggregated-metric): Dropdown broken on click

- docs/sources/access/_index.md
- docs/sources/get-started/_index.md
- docs/sources/labels-and-fields/_index.md
- docs/sources/ordering/_index.md
- docs/sources/troubleshooting/_index.md
- docs/sources/viewing-json-logs/_index.md
Addressing review comments from #1248  that were not addressed before PR was merged.
Also addresses a few more typos noticed while reviewing the docs, including one missing image due to a typo.
> docs: Addressing review comments #1248

- .github/workflows/bundle-stats.yml
- .github/workflows/ci.yml
- package.json
- webpack.config.ts
- yarn.lock
- #1165 
Successful run, it should show up on the PR once it's in main
> chore(bundle-stats): swap bundlewatch for cp gha bundle-stats

- docs/sources/viewing-json-logs/_index.md
Changed the word dashboards to visualizations
> docs: Quick fix: Dashboards > Visualizations

- .github/workflows/publish.yml
> chore(plugin-ci-workflows): publish skip playwright

- src/Components/ServiceScene/Breakdowns/AddToInvestigationButton.tsx
Fix jsonFields variable not interpolating in investigation queries.
> fix(investigations): interpolate jsonFields

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Would we like github issue templates? 🧐🤔
> chore(gh issues): update issue templates

- CHANGELOG.md
- package.json
> chore(version): 1.0.17

- generator/main.go
add optional `--token` arg to the generator, which is necessary when using against GEL
> feat: add token to generator

- docs/sources/patterns/_index.md
While reading the docs the other day I spotted an incomplete sentence.
> docs: fix incomplete sentence

- .github/workflows/format-gh-issues.yml
> chore(gha): github permissions are fun

- .github/workflows/format-gh-issues.yml
Actual proof it works this time https://github.com/grafana/test-release-gh-actions/actions/runs/15644382247/job/44078904692 🥲
> chore(gha): id-token permission

- src/Components/ServiceScene/LogsVolumePanel.tsx
Fixes: https://github.com/grafana/logs-drilldown/issues/1362
> fix(logs-volume): don't run volume query when collapsed

- src/Components/EmbeddedLogsExploration/EmbeddedLogs.tsx
- src/Components/IndexScene/IndexScene.tsx
- src/Components/IndexScene/types.ts
- src/Components/Pages.tsx
- tests/appNavigation.spec.ts
- tests/embed.spec.ts
- tests/exploreServicesJsonBreakDown.spec.ts
Allow embedded Logs Drilldown parse default line filters from query string prop.
> feat(Embbedding): open embedding API for default line filters

- src/Components/ServiceScene/JSONPanel/JSONFilterNestedNodeButton.tsx
- src/Components/ServiceScene/JSONPanel/JSONFilterValueButton.tsx
- src/Components/Table/Table.tsx
- tests/exploreServicesJsonBreakDown.spec.ts
> fix(JSON): selected buttons not showing active style

- package.json
- playwright.config.ts
- src/Components/Buttons/CopyToClipboardButton.tsx
- src/Components/ServiceScene/JSONPanel/ItemString.tsx
- src/Components/ServiceScene/JSONPanel/LogsJsonComponent.tsx
- src/Components/ServiceScene/LogsJsonScene.tsx
- src/services/fields.ts
- tests/exploreServicesJsonBreakDown.spec.ts
- yarn.lock
Fixes: https://github.com/grafana/logs-drilldown/issues/1394
Requires library updates: https://github.com/gtk-grafana/react-json-tree/pull/21, https://github.com/gtk-grafana/react-json-tree/pull/22
Working as expected, opening for review, but I'm going to add e2e coverage in the morning.
Need to add selected/hover styles, but I'll tackle that in another branch.
> feat(JSON): share link to line

- provisioning/datasources/default.yaml
- src/Components/ServiceScene/JSONPanel/ItemString.tsx
- src/Components/ServiceScene/JSONPanel/JsonLinkButton.tsx
- src/Components/ServiceScene/JSONPanel/LabelRenderer.tsx
- src/Components/ServiceScene/JSONPanel/ValueRenderer.tsx
- src/Components/ServiceScene/LogsJsonScene.tsx
- src/services/JSONViz.ts
- src/services/derivedFields.ts
- src/services/narrowing.ts
- tests/exploreServicesJsonBreakDown.spec.ts
Fixes: https://github.com/grafana/logs-drilldown/issues/1419
> feat(JSON): links

- src/Components/ServiceScene/Breakdowns/AddToFiltersButton.tsx
> fix(ad-hoc filters): fix duplicate filters

- src/Components/ServiceScene/ServiceScene.tsx
- src/services/analytics.ts
Send event on logs query complete/error
> chore(analytics): on query event

- src/Components/ServiceScene/JSONLogsScene.tsx
- src/Components/ServiceScene/LogsPanelScene.tsx
- src/Components/ServiceScene/LogsTableScene.tsx
- src/services/analytics.ts
Follow up to https://github.com/grafana/logs-drilldown/pull/1439
> feat(analytics): report viz init once

- src/Components/ServiceScene/JSONLogsScene.tsx
- src/Components/ServiceScene/JSONPanel/LogsJSONComponent.tsx
- src/Components/ServiceScene/LineLimitScene.tsx
- src/Components/ServiceScene/LogsListScene.tsx
- src/Components/ServiceScene/LogsPanelScene.tsx
- src/Components/ServiceScene/LogsTableScene.tsx
- tests/exploreServicesJsonBreakDown.spec.ts
- #1535 
- Updated error copy
- Added invalidation border
> feat(LineLimitScene): error message, invalidation state
